#!/usr/bin/env bash
# Smoke script for Phase 17 — dockyard CLI skeleton + dockyard new.
# One assertion per acceptance criterion (master plan Phase 17):
#   - `dockyard new` produces a project
#   - that project builds
#   - that project serves (boots as an MCP server) — proven by its contract test
#   - the no-template path is first-class (no --template required)
#   - the scaffold's contracts are generated, not hand-written (P1)
#   - the S1 fold-in: a handler-emitted log event correlates to its tool.call
# A check against an unbuilt surface skip()s, never fail()s — see common.sh.
set -uo pipefail
cd "$(dirname "$0")/../.."
. scripts/smoke/common.sh

echo "smoke: phase-17 dockyard CLI skeleton + new"

REPO_ROOT="$(pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# --- the dockyard binary -----------------------------------------------------
if [ ! -f cmd/dockyard/main.go ]; then
  skip "cmd/dockyard/main.go absent — CLI phase not landed"
  smoke_summary
  exit $?
fi

if CGO_ENABLED=0 go build -o "$WORK/dockyard" ./cmd/dockyard 2>"$WORK/build.log"; then
  ok "dockyard binary builds CGo-free"
else
  fail "dockyard binary build failed"; sed 's/^/    /' "$WORK/build.log"
  smoke_summary; exit $?
fi
DOCKYARD="$WORK/dockyard"

# --- the cobra tree exposes `new` --------------------------------------------
# Capture help to a file first: piping straight into `grep -q` can SIGPIPE the
# binary, and `set -o pipefail` would then read that as a failure.
"$DOCKYARD" --help >"$WORK/help.txt" 2>&1 || true
if grep -q '\bnew\b' "$WORK/help.txt"; then
  ok "cobra root command exposes 'new'"
else
  fail "'dockyard --help' does not list the 'new' command"
fi

# --- `dockyard new` produces a project (no --template — first-class path) ----
PROJ="$WORK/proj"
mkdir -p "$PROJ"
if "$DOCKYARD" new smoke-server --dir "$PROJ" --dockyard-path "$REPO_ROOT" \
     >"$WORK/new.log" 2>&1; then
  ok "dockyard new (no --template) produces a project"
else
  fail "dockyard new failed"; sed 's/^/    /' "$WORK/new.log"
  smoke_summary; exit $?
fi
SRV="$PROJ/smoke-server"

# manifest + example tool + main exist
if [ -f "$SRV/dockyard.app.yaml" ] && [ -f "$SRV/main.go" ] && [ -f "$SRV/greet.go" ]; then
  ok "scaffold includes manifest, main, and an example tool"
else
  fail "scaffold is missing manifest / main / example tool"
fi

# --- the scaffold's contracts are GENERATED, not hand-written (P1) -----------
if grep -q 'Code generated by dockyard; DO NOT EDIT.' \
     "$SRV/internal/contracts/contracts.ts" 2>/dev/null \
   && [ -f "$SRV/internal/contracts/greet_input.schema.json" ]; then
  ok "scaffold ships generated contract artifacts (schema + TypeScript)"
else
  fail "scaffold contract artifacts are missing or not marked generated"
fi

# --- the scaffolded project builds and serves --------------------------------
if ( cd "$SRV" && CGO_ENABLED=0 go mod tidy && CGO_ENABLED=0 go build ./... ) \
     >"$WORK/proj-build.log" 2>&1; then
  ok "the scaffolded project builds"
else
  fail "the scaffolded project does not build"; sed 's/^/    /' "$WORK/proj-build.log"
fi

# The contract test boots the example tool through the runtime — serves proof.
if ( cd "$SRV" && CGO_ENABLED=0 go test ./... ) >"$WORK/proj-test.log" 2>&1; then
  ok "the scaffolded project's contract test passes (it serves)"
else
  fail "the scaffolded project's contract test failed"; sed 's/^/    /' "$WORK/proj-test.log"
fi

# --- S1 fold-in: handler log event correlates to its tool.call ---------------
if CGO_ENABLED=1 go test -race -count=1 \
     -run 'TestLogBridge_HandlerLogCorrelatesToToolCall' \
     ./runtime/server/ >"$WORK/s1.log" 2>&1; then
  ok "S1: a handler-emitted log event is trace-correlated to its tool.call"
else
  fail "S1 trace-correlation test failed"; sed 's/^/    /' "$WORK/s1.log"
fi

smoke_summary
