#!/usr/bin/env bash
# Smoke script for Phase 05 — Go → TypeScript codegen + drift cross-check.
# One assertion per acceptance criterion (docs/plans/phase-05-typescript-codegen.md).
# A check against an unbuilt surface skips rather than fails — see common.sh.
set -uo pipefail
cd "$(dirname "$0")/../.."
. scripts/smoke/common.sh

echo "smoke: phase-05 typescript-codegen"

# 1. The TypeScript generator and drift cross-check source files exist.
if [ -f internal/codegen/typescript.go ] && [ -f internal/codegen/drift.go ]; then
  ok "typescript generator + drift cross-check exist"
else
  skip "phase-05 codegen files not built"
fi

# 2. gzuidhof/tygo is a direct dependency (the pure-Go Go->TS generator).
if [ -f internal/codegen/typescript.go ]; then
  if grep -q 'github.com/gzuidhof/tygo v' go.mod \
     && ! grep -q 'github.com/gzuidhof/tygo v.* // indirect' go.mod; then
    ok "gzuidhof/tygo is a direct dependency"
  else
    fail "gzuidhof/tygo is not a direct dependency in go.mod"
  fi
else
  skip "phase-05 not built — dependency check deferred"
fi

# 3. The TypeScript golden fixtures exist, are non-empty, and carry the
#    Code-generated header.
if compgen -G 'internal/codegen/testdata/*.ts.golden' >/dev/null; then
  hdr_ok=1
  for f in internal/codegen/testdata/*.ts.golden; do
    [ -s "$f" ] || hdr_ok=0
    head -1 "$f" | grep -q 'Code generated by dockyard; DO NOT EDIT.' || hdr_ok=0
  done
  if [ "$hdr_ok" -eq 1 ]; then
    ok "TypeScript golden fixtures exist with the generated header"
  else
    fail "a TypeScript golden fixture is empty or missing the generated header"
  fi
else
  skip "TypeScript golden fixtures not built"
fi

# 4. The codegen package builds CGo-free (no Node, no CGo on the codegen path).
if [ -f internal/codegen/typescript.go ]; then
  if CGO_ENABLED=0 go build ./internal/codegen/... >/dev/null 2>&1; then
    ok "codegen builds CGo-free"
  else
    fail "internal/codegen does not build with CGO_ENABLED=0"
  fi
else
  skip "phase-05 not built — build check deferred"
fi

# 5. The codegen tests pass — TS generation, both drift checks, golden output.
if [ -f internal/codegen/typescript_test.go ] && [ -f internal/codegen/drift_test.go ]; then
  if go test ./internal/codegen/... >/dev/null 2>&1; then
    ok "codegen tests pass (TS generation + drift cross-check + golden)"
  else
    fail "codegen tests fail"
  fi
else
  skip "phase-05 tests not built"
fi

# 6. The Phase 05 drift integration test passes (schema + TS -> cross-check).
if [ -f test/integration/phase05_drift_test.go ]; then
  if go test ./test/integration/ -run Phase05 >/dev/null 2>&1; then
    ok "phase-05 drift cross-check integration test passes"
  else
    fail "phase-05 integration test fails"
  fi
else
  skip "phase-05 integration test not built"
fi

smoke_summary
