package codegen_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hurtener/dockyard/internal/codegen"
)

// generatedTSMarker is the canonical first line of every generated TypeScript
// file; AGENTS.md §5 mandates the "Code generated ... DO NOT EDIT." marker.
const generatedTSMarker = "// Code generated by dockyard; DO NOT EDIT."

// --- contract source fixtures ----------------------------------------------

const tsScalars = "// Profile is a contract.\n" +
	"type Profile struct {\n" +
	"\tName    string  `json:\"name\"`\n" +
	"\tAge     int     `json:\"age\"`\n" +
	"\tBalance float64 `json:\"balance\"`\n" +
	"\tActive  bool    `json:\"active\"`\n" +
	"\tNick    string  `json:\"nick,omitempty\"`\n" +
	"}\n"

const tsNested = "type Line struct {\n" +
	"\tSKU   string  `json:\"sku\"`\n" +
	"\tPrice float64 `json:\"price\"`\n" +
	"}\n\n" +
	"type Order struct {\n" +
	"\tID    string `json:\"id\"`\n" +
	"\tLines []Line `json:\"lines\"`\n" +
	"}\n"

// --- TypeScriptForSource ---------------------------------------------------

func TestTypeScriptForSource_Header(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	if !strings.HasPrefix(string(got), generatedTSMarker) {
		t.Errorf("output does not start with the generated marker:\n%s", got)
	}
	if !strings.HasSuffix(string(got), "\n") || strings.HasSuffix(string(got), "\n\n") {
		t.Errorf("output must end with exactly one trailing newline")
	}
}

func TestTypeScriptForSource_Scalars(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	for _, want := range []string{
		"export interface Profile {",
		"name: string;",
		"age: number",
		"balance: number",
		"active: boolean;",
		"nick?: string;", // omitempty ⇒ optional
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated TS missing %q\n%s", want, s)
		}
	}
}

func TestTypeScriptForSource_NestedAndSlice(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "export interface Line {") || !strings.Contains(s, "export interface Order {") {
		t.Errorf("both interfaces should be generated:\n%s", s)
	}
	if !strings.Contains(s, "lines: Line[];") {
		t.Errorf("slice field should render as Line[]:\n%s", s)
	}
}

func TestTypeScriptForSource_Deterministic(t *testing.T) {
	t.Parallel()
	a, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("first generation: %v", err)
	}
	b, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("second generation: %v", err)
	}
	if string(a) != string(b) {
		t.Errorf("TypeScriptForSource is not deterministic:\n--- a ---\n%s\n--- b ---\n%s", a, b)
	}
}

func TestTypeScriptForSource_AcceptsPackageClause(t *testing.T) {
	t.Parallel()
	// A full file with a package clause and imports must work — TypeScriptForDir
	// reads real source files.
	src := "// Package contracts is the source of truth.\n" +
		"package contracts\n\n" +
		"import \"time\"\n\n" +
		"var _ = time.Now\n\n" +
		tsScalars
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatalf("TypeScriptForSource with package clause: %v", err)
	}
	if !strings.Contains(string(got), "export interface Profile {") {
		t.Errorf("type declaration not generated from a full-file source:\n%s", got)
	}
	if strings.Contains(string(got), "time") {
		t.Errorf("import-derived noise leaked into the output:\n%s", got)
	}
}

func TestTypeScriptForSource_WithIndent(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars, codegen.WithIndent("    "))
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	if !strings.Contains(string(got), "\n    name: string;") {
		t.Errorf("WithIndent(4 spaces) not honoured:\n%s", got)
	}
}

func TestTypeScriptForSource_WithNullOptional(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars, codegen.WithNullOptional())
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "nick: string | null;") {
		t.Errorf("WithNullOptional should render optional fields as `T | null`:\n%s", s)
	}
	if strings.Contains(s, "nick?:") {
		t.Errorf("WithNullOptional should not emit the `?` optional marker:\n%s", s)
	}
}

func TestTypeScriptForSource_InvalidSource(t *testing.T) {
	t.Parallel()
	_, err := codegen.TypeScriptForSource("type Broken struct { this is not go")
	if err == nil {
		t.Fatal("expected an error for unparseable Go source")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

// TestGeneratedTSIsStructurallyValid checks the golden TypeScript fixtures are
// structurally valid TS: balanced braces, every declaration is a recognised
// export, and no `any /* ... */` fallback markers (tygo emits those for an
// unmapped Go type — a contract that produced one would not be cleanly typed).
// This is a hermetic stand-in for a full `tsc` compile; the codegen path stays
// Node-free (RFC §6.2, Design A).
func TestGeneratedTSIsStructurallyValid(t *testing.T) {
	t.Parallel()
	entries, err := os.ReadDir("testdata")
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}
	var checked int
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".ts.golden") {
			continue
		}
		checked++
		t.Run(e.Name(), func(t *testing.T) {
			t.Parallel()
			raw, err := os.ReadFile(filepath.Join("testdata", e.Name())) //nolint:gosec // fixed testdata path
			if err != nil {
				t.Fatalf("read fixture: %v", err)
			}
			ts := string(raw)
			assertBalanced(t, ts)
			if strings.Contains(ts, "any /*") {
				t.Errorf("fixture %s contains an unmapped-type fallback marker `any /* ... */`", e.Name())
			}
			if !strings.HasPrefix(ts, generatedTSMarker) {
				t.Errorf("fixture %s missing the generated marker", e.Name())
			}
		})
	}
	if checked == 0 {
		t.Fatal("no .ts.golden fixtures found — run -update")
	}
}

func assertBalanced(t *testing.T, ts string) {
	t.Helper()
	depth := 0
	for _, r := range ts {
		switch r {
		case '{':
			depth++
		case '}':
			depth--
			if depth < 0 {
				t.Fatalf("unbalanced braces: a `}` with no opener")
			}
		}
	}
	if depth != 0 {
		t.Fatalf("unbalanced braces: %d unclosed `{`", depth)
	}
}

// --- TypeScriptForDir ------------------------------------------------------

func TestTypeScriptForDir(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	// Two contract files plus a test file that must be ignored. Files are read
	// in sorted name order: a_types.go before b_types.go.
	writeFile(t, dir, "b_types.go", "package contracts\n\n"+
		"type Beta struct {\n\tID string `json:\"id\"`\n}\n")
	writeFile(t, dir, "a_types.go", "package contracts\n\n"+
		"type Alpha struct {\n\tName string `json:\"name\"`\n}\n")
	writeFile(t, dir, "x_types_test.go", "package contracts\n\n"+
		"type ShouldBeIgnored struct {\n\tX int `json:\"x\"`\n}\n")

	got, err := codegen.TypeScriptForDir(dir)
	if err != nil {
		t.Fatalf("TypeScriptForDir: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "export interface Alpha {") || !strings.Contains(s, "export interface Beta {") {
		t.Errorf("both contract files should be generated:\n%s", s)
	}
	if strings.Contains(s, "ShouldBeIgnored") {
		t.Errorf("_test.go file should be ignored:\n%s", s)
	}
	// Sorted order: Alpha (a_types.go) precedes Beta (b_types.go).
	if strings.Index(s, "Alpha") > strings.Index(s, "Beta") {
		t.Errorf("declarations should appear in sorted-filename order:\n%s", s)
	}
}

func TestTypeScriptForDir_Empty(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	_, err := codegen.TypeScriptForDir(dir)
	if err == nil {
		t.Fatal("expected an error for a directory with no contract files")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

func TestTypeScriptForDir_Missing(t *testing.T) {
	t.Parallel()
	_, err := codegen.TypeScriptForDir(filepath.Join(t.TempDir(), "does-not-exist"))
	if err == nil {
		t.Fatal("expected an error for a missing directory")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}
