package codegen_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hurtener/dockyard/internal/codegen"
)

// generatedTSMarker is the canonical first line of every generated TypeScript
// file; AGENTS.md §5 mandates the "Code generated ... DO NOT EDIT." marker.
const generatedTSMarker = "// Code generated by dockyard; DO NOT EDIT."

// --- contract source fixtures ----------------------------------------------

const tsScalars = "// Profile is a contract.\n" +
	"type Profile struct {\n" +
	"\tName    string  `json:\"name\"`\n" +
	"\tAge     int     `json:\"age\"`\n" +
	"\tBalance float64 `json:\"balance\"`\n" +
	"\tActive  bool    `json:\"active\"`\n" +
	"\tNick    string  `json:\"nick,omitempty\"`\n" +
	"}\n"

const tsNested = "type Line struct {\n" +
	"\tSKU   string  `json:\"sku\"`\n" +
	"\tPrice float64 `json:\"price\"`\n" +
	"}\n\n" +
	"type Order struct {\n" +
	"\tID    string `json:\"id\"`\n" +
	"\tLines []Line `json:\"lines\"`\n" +
	"}\n"

// --- TypeScriptForSource ---------------------------------------------------

func TestTypeScriptForSource_Header(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	if !strings.HasPrefix(string(got), generatedTSMarker) {
		t.Errorf("output does not start with the generated marker:\n%s", got)
	}
	if !strings.HasSuffix(string(got), "\n") || strings.HasSuffix(string(got), "\n\n") {
		t.Errorf("output must end with exactly one trailing newline")
	}
}

func TestTypeScriptForSource_Scalars(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	for _, want := range []string{
		"export interface Profile {",
		"name: string;",
		"age: number",
		"balance: number",
		"active: boolean;",
		"nick?: string;", // omitempty ⇒ optional
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated TS missing %q\n%s", want, s)
		}
	}
}

func TestTypeScriptForSource_NestedAndSlice(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "export interface Line {") || !strings.Contains(s, "export interface Order {") {
		t.Errorf("both interfaces should be generated:\n%s", s)
	}
	if !strings.Contains(s, "lines: Line[];") {
		t.Errorf("slice field should render as Line[]:\n%s", s)
	}
}

func TestTypeScriptForSource_Deterministic(t *testing.T) {
	t.Parallel()
	a, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("first generation: %v", err)
	}
	b, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("second generation: %v", err)
	}
	if string(a) != string(b) {
		t.Errorf("TypeScriptForSource is not deterministic:\n--- a ---\n%s\n--- b ---\n%s", a, b)
	}
}

func TestTypeScriptForSource_AcceptsPackageClause(t *testing.T) {
	t.Parallel()
	// A full file with a package clause and imports must work — TypeScriptForDir
	// reads real source files.
	src := "// Package contracts is the source of truth.\n" +
		"package contracts\n\n" +
		"import \"time\"\n\n" +
		"var _ = time.Now\n\n" +
		tsScalars
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatalf("TypeScriptForSource with package clause: %v", err)
	}
	if !strings.Contains(string(got), "export interface Profile {") {
		t.Errorf("type declaration not generated from a full-file source:\n%s", got)
	}
	if strings.Contains(string(got), "time") {
		t.Errorf("import-derived noise leaked into the output:\n%s", got)
	}
}

func TestTypeScriptForSource_WithIndent(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars, codegen.WithIndent("    "))
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	if !strings.Contains(string(got), "\n    name: string;") {
		t.Errorf("WithIndent(4 spaces) not honoured:\n%s", got)
	}
}

func TestTypeScriptForSource_WithNullOptional(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars, codegen.WithNullOptional())
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "nick: string | null;") {
		t.Errorf("WithNullOptional should render optional fields as `T | null`:\n%s", s)
	}
	if strings.Contains(s, "nick?:") {
		t.Errorf("WithNullOptional should not emit the `?` optional marker:\n%s", s)
	}
}

func TestTypeScriptForSource_InvalidSource(t *testing.T) {
	t.Parallel()
	_, err := codegen.TypeScriptForSource("type Broken struct { this is not go")
	if err == nil {
		t.Fatal("expected an error for unparseable Go source")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

// TestTypeScriptForSource_MalformedStructTagNoPanic is a Phase 21.5 regression
// test: the FuzzTypeScriptForSource target found that a struct field carrying a
// syntactically invalid struct tag drove the tygo dependency to panic ("bad
// syntax for struct tag pair") rather than return an error. TypeScriptForSource
// must now contain that panic and return an ErrTypeScriptGen error — a
// malformed contract file fails the codegen step cleanly, never crashes the
// process (CLAUDE.md §13).
func TestTypeScriptForSource_MalformedStructTagNoPanic(t *testing.T) {
	t.Parallel()
	// The tag `0` (a bare backtick-quoted value, not a key:"value" pair) is the
	// minimised crasher the fuzzer surfaced.
	const crasher = "type A0 struct {A0`0`} "
	_, err := codegen.TypeScriptForSource(crasher)
	if err == nil {
		t.Fatal("expected an error for a malformed struct tag, got nil")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

// TestGeneratedTSIsStructurallyValid checks the golden TypeScript fixtures are
// structurally valid TS: balanced braces, every declaration is a recognised
// export, and no `any /* ... */` fallback markers (tygo emits those for an
// unmapped Go type — a contract that produced one would not be cleanly typed).
// This is a hermetic stand-in for a full `tsc` compile; the codegen path stays
// Node-free (RFC §6.2, Design A).
func TestGeneratedTSIsStructurallyValid(t *testing.T) {
	t.Parallel()
	entries, err := os.ReadDir("testdata")
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}
	var checked int
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".ts.golden") {
			continue
		}
		checked++
		t.Run(e.Name(), func(t *testing.T) {
			t.Parallel()
			raw, err := os.ReadFile(filepath.Join("testdata", e.Name())) //nolint:gosec // fixed testdata path
			if err != nil {
				t.Fatalf("read fixture: %v", err)
			}
			ts := string(raw)
			assertBalanced(t, ts)
			if strings.Contains(ts, "any /*") {
				t.Errorf("fixture %s contains an unmapped-type fallback marker `any /* ... */`", e.Name())
			}
			if !strings.HasPrefix(ts, generatedTSMarker) {
				t.Errorf("fixture %s missing the generated marker", e.Name())
			}
		})
	}
	if checked == 0 {
		t.Fatal("no .ts.golden fixtures found — run -update")
	}
}

func assertBalanced(t *testing.T, ts string) {
	t.Helper()
	depth := 0
	for _, r := range ts {
		switch r {
		case '{':
			depth++
		case '}':
			depth--
			if depth < 0 {
				t.Fatalf("unbalanced braces: a `}` with no opener")
			}
		}
	}
	if depth != 0 {
		t.Fatalf("unbalanced braces: %d unclosed `{`", depth)
	}
}

// --- embedded-struct flattening (finding 4 / D-051) ------------------------

func TestTypeScriptForSource_EmbeddedStructFlattened(t *testing.T) {
	t.Parallel()
	src := "// Base carries shared fields.\n" +
		"type Base struct {\n" +
		"\tID   string `json:\"id\"`\n" +
		"\tKind string `json:\"kind\"`\n" +
		"}\n\n" +
		"// Widget embeds Base.\n" +
		"type Widget struct {\n" +
		"\tBase\n" +
		"\tTitle string `json:\"title\"`\n" +
		"}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	// The embedded struct's fields are inlined into Widget.
	for _, want := range []string{"id: string;", "kind: string;", "title: string;"} {
		if !strings.Contains(s, want) {
			t.Errorf("embedded field %q should be inlined into Widget:\n%s", want, s)
		}
	}
	// tygo's default `Base: Base;` named-property form must NOT appear.
	if strings.Contains(s, "Base: Base") {
		t.Errorf("embedded struct must be flattened, not emitted as a named property:\n%s", s)
	}
}

func TestTypeScriptForSource_EmbeddedTransitiveAndShadowing(t *testing.T) {
	t.Parallel()
	// AuditSpan embeds AuditEvent (which embeds AuditBase) and re-declares `kind`
	// — Go's "outer wins" promotion rule. The flattened interface must carry
	// `kind` exactly once.
	src := "type Inner struct {\n" +
		"\tID   string `json:\"id\"`\n" +
		"\tKind string `json:\"kind\"`\n" +
		"}\n\n" +
		"type Mid struct {\n" +
		"\tInner\n" +
		"\tTitle string `json:\"title\"`\n" +
		"}\n\n" +
		"type Outer struct {\n" +
		"\tMid\n" +
		"\tKind     string `json:\"kind\"`\n" +
		"\tDuration int    `json:\"duration\"`\n" +
		"}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	outer := s[strings.Index(s, "export interface Outer"):]
	outer = outer[:strings.Index(outer, "}")]
	if n := strings.Count(outer, "kind"); n != 1 {
		t.Errorf("`kind` should appear exactly once in Outer (outer wins), got %d:\n%s", n, outer)
	}
	for _, want := range []string{"id", "title", "duration"} {
		if !strings.Contains(outer, want) {
			t.Errorf("transitively promoted field %q missing from Outer:\n%s", want, outer)
		}
	}
}

func TestTypeScriptForSource_EmbeddedForeignTypeLeftAlone(t *testing.T) {
	t.Parallel()
	// An embedded type that is not a locally declared struct cannot be flattened
	// — its fields are not visible here — so it is left for tygo.
	src := "type Widget struct {\n" +
		"\tsync.Mutex\n" +
		"\tName string `json:\"name\"`\n" +
		"}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	if !strings.Contains(string(got), "name: string;") {
		t.Errorf("the non-embedded field should still render:\n%s", got)
	}
}

// --- TypeScriptForDir ------------------------------------------------------

func TestTypeScriptForDir(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	// Two contract files plus a test file that must be ignored. Files are read
	// in sorted name order: a_types.go before b_types.go.
	writeFile(t, dir, "b_types.go", "package contracts\n\n"+
		"type Beta struct {\n\tID string `json:\"id\"`\n}\n")
	writeFile(t, dir, "a_types.go", "package contracts\n\n"+
		"type Alpha struct {\n\tName string `json:\"name\"`\n}\n")
	writeFile(t, dir, "x_types_test.go", "package contracts\n\n"+
		"type ShouldBeIgnored struct {\n\tX int `json:\"x\"`\n}\n")

	got, err := codegen.TypeScriptForDir(dir)
	if err != nil {
		t.Fatalf("TypeScriptForDir: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "export interface Alpha {") || !strings.Contains(s, "export interface Beta {") {
		t.Errorf("both contract files should be generated:\n%s", s)
	}
	if strings.Contains(s, "ShouldBeIgnored") {
		t.Errorf("_test.go file should be ignored:\n%s", s)
	}
	// Sorted order: Alpha (a_types.go) precedes Beta (b_types.go).
	if strings.Index(s, "Alpha") > strings.Index(s, "Beta") {
		t.Errorf("declarations should appear in sorted-filename order:\n%s", s)
	}
}

func TestTypeScriptForDir_Empty(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	_, err := codegen.TypeScriptForDir(dir)
	if err == nil {
		t.Fatal("expected an error for a directory with no contract files")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

func TestTypeScriptForDir_Missing(t *testing.T) {
	t.Parallel()
	_, err := codegen.TypeScriptForDir(filepath.Join(t.TempDir(), "does-not-exist"))
	if err == nil {
		t.Fatal("expected an error for a missing directory")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}
