package codegen

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"go/types"
	"hash/fnv"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/fatih/structtag"
	"github.com/gzuidhof/tygo/tygo"
	"golang.org/x/tools/go/packages"
)

// generatedTSHeader is the banner placed at the top of every generated
// TypeScript file. The first line is the canonical `Code generated … DO NOT
// EDIT.` marker (AGENTS.md §5) — tools and reviewers recognise it, and it tells
// an app author the file is regenerated, never hand-edited (RFC §6.2).
const generatedTSHeader = `// Code generated by dockyard; DO NOT EDIT.
//
// TypeScript contract types — the UI-facing half of the Design A codegen
// pipeline (RFC §6.2). Generated from the Go contract structs by github.com/
// gzuidhof/tygo. The Go struct is the single source of truth (P1); regenerate
// with ` + "`dockyard generate`" + ` and never edit this file by hand.
`

const literalDashTagSentinel = "dockyard©json©literal©dash"

var (
	jsonStructTagRE    = regexp.MustCompile(`(?:^|[[:space:]])json:"(?:\\.|[^"\\])*"`)
	literalDashTSKeyRE = regexp.MustCompile(`(?m)^([\t ]*)'` + regexp.QuoteMeta(literalDashTagSentinel) + `'([?]?:)`)
)

// ErrTypeScriptGen is returned when Go contract source cannot be converted to
// TypeScript. It wraps the underlying tygo parse/convert failure so callers can
// branch with errors.Is.
var ErrTypeScriptGen = errors.New("dockyard/internal/codegen: typescript generation failed")

// tsConfig holds the resolved TypeScript-generation options.
type tsConfig struct {
	indent       string
	optionalType string // "" (undefined) or "null"
}

// TSOption configures TypeScript generation.
type TSOption func(*tsConfig)

// WithIndent sets the indentation string of the generated TypeScript. The
// default is two spaces, matching the JSON Schema marshaller (codegen.Marshal)
// so both generated artifacts share a house style.
func WithIndent(indent string) TSOption {
	return func(c *tsConfig) { c.indent = indent }
}

// WithNullOptional renders optional fields as `T | null` rather than the tygo
// default `field?: T` (`undefined`). Use it when the consuming UI deserializes
// JSON that carries explicit nulls for absent optional fields.
func WithNullOptional() TSOption {
	return func(c *tsConfig) { c.optionalType = "null" }
}

func resolveTSConfig(opts []TSOption) tsConfig {
	c := tsConfig{indent: "  "}
	for _, opt := range opts {
		opt(&c)
	}
	return c
}

// TypeScriptForSource converts a fragment of Go contract source — the type
// declarations of a contracts package — into deterministic TypeScript.
//
// goSource is ordinary Go source: a package clause is permitted and ignored,
// imports are stripped, and only top-level type/const declarations are
// converted (tygo reads the Go AST, not reflection, so doc comments, enums and
// constants survive — brief 06 §2.4). The returned bytes carry the
// Code-generated header and end with a trailing newline; identical input always
// yields byte-identical output, which is what makes the golden tests and the
// drift cross-check meaningful (RFC §6.2, brief 06 R1).
//
// On a tygo parse or convert failure the error wraps ErrTypeScriptGen.
//
// Malformed Go source — a struct field carrying a syntactically invalid struct
// tag is the known case — can drive the tygo dependency to panic rather than
// return an error (tygo parses tags via reflect.StructTag, which panics on a
// malformed pair). TypeScriptForSource contains that panic and converts it to
// an ErrTypeScriptGen error: a malformed contract file must fail the codegen
// step cleanly, never crash the process (CLAUDE.md §13 — never panic across a
// process boundary). Found by the Phase 21.5 FuzzTypeScriptForSource target.
func TypeScriptForSource(goSource string, opts ...TSOption) ([]byte, error) {
	return typeScriptForSource(goSource, false, opts...)
}

func typeScriptForSource(goSource string, normalized bool, opts ...TSOption) ([]byte, error) {
	cfg := resolveTSConfig(opts)

	decls, err := typeDeclSourceForFile(goSource, importedTypes{}, true, !normalized, true)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrTypeScriptGen, err)
	}

	pc := tygo.PackageConfig{
		Path:             "contracts",
		Indent:           cfg.indent,
		PreserveComments: "default",
		EnumStyle:        "union",
	}
	if cfg.optionalType == "null" {
		pc.OptionalType = "null"
	}

	body, err := convertGoToTypeScript(decls, pc)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrTypeScriptGen, err)
	}
	body = literalDashTSKeyRE.ReplaceAllString(body, "$1'-'$2")

	return assembleTS(body), nil
}

// convertGoToTypeScript calls tygo.ConvertGoToTypescript under a recover guard:
// tygo panics (rather than returning an error) on some malformed input — a
// struct field with a syntactically invalid struct tag is the known case. The
// recover turns such a panic into an ordinary error so the caller's
// `%w: ErrTypeScriptGen` wrapping holds for every failure mode.
func convertGoToTypeScript(decls string, pc tygo.PackageConfig) (body string, err error) {
	defer func() {
		if r := recover(); r != nil {
			body = ""
			err = fmt.Errorf("tygo conversion panicked on malformed input: %v", r)
		}
	}()
	return tygo.ConvertGoToTypescript(decls, pc)
}

// TypeScriptForDir reads the .go files of a contracts directory and generates
// TypeScript for the type declarations they contain. It is the seam Phase 18's
// `dockyard generate` calls with a project's `internal/contracts` directory.
//
// Files are read in sorted filename order and their type declarations
// concatenated in that order, so the generated output is deterministic
// regardless of filesystem iteration order. Test files (`_test.go`) and
// generated files are skipped.
func TypeScriptForDir(dir string, opts ...TSOption) ([]byte, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("%w: read dir %s: %w", ErrTypeScriptGen, dir, err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		n := e.Name()
		if !strings.HasSuffix(n, ".go") || strings.HasSuffix(n, "_test.go") {
			continue
		}
		names = append(names, n)
	}
	sort.Strings(names)
	if len(names) == 0 {
		return nil, fmt.Errorf("%w: no .go contract files in %s", ErrTypeScriptGen, dir)
	}
	if err := rejectLocalCustomJSONEncoding(dir, names[0]); err != nil {
		return nil, fmt.Errorf("%w: %w", ErrTypeScriptGen, err)
	}

	resolver := newImportedTypeResolver(dir)
	var combined strings.Builder
	for _, n := range names {
		path := filepath.Join(dir, n)
		raw, readErr := os.ReadFile(path) //nolint:gosec // path is composed from a caller-supplied contracts dir
		if readErr != nil {
			return nil, fmt.Errorf("%w: read %s: %w", ErrTypeScriptGen, path, readErr)
		}
		if strings.HasSuffix(n, ".generated.go") || generatedGoSource(raw) {
			continue
		}
		imported, resolveErr := resolver.importedTypesForFile(n, raw)
		if resolveErr != nil {
			return nil, fmt.Errorf("%w: resolve imported byte aliases in %s: %w", ErrTypeScriptGen, path, resolveErr)
		}
		// Defer json:",string" rewriting until typeScriptForSource parses the
		// combined declaration set below. Alias and named-scalar declarations are
		// package scoped and may live in a different canonical source file.
		decls, declErr := typeDeclSourceForFile(string(raw), imported, false, true, false)
		if declErr != nil {
			return nil, fmt.Errorf("%w: %s: %w", ErrTypeScriptGen, path, declErr)
		}
		if strings.TrimSpace(decls) == "" {
			continue
		}
		if combined.Len() > 0 {
			combined.WriteString("\n")
		}
		combined.WriteString(decls)
	}
	if strings.TrimSpace(combined.String()) == "" {
		return nil, fmt.Errorf("%w: %s declares no contract types", ErrTypeScriptGen, dir)
	}
	return typeScriptForSource(combined.String(), true, opts...)
}

// typeDeclSource parses Go source and re-renders only its top-level type and
// const declarations, dropping the package clause, imports, functions and
// variables. tygo's ConvertGoToTypescript expects a bare declaration fragment;
// passing it a full file with a package clause fails to parse, and passing it
// functions or imports produces noise. Re-printing through go/printer also
// normalises formatting, which keeps the generated TypeScript deterministic.
//
// Before re-rendering, embedded (anonymous) struct fields are flattened: an
// anonymous field whose type is another struct declared in the package source is
// replaced, in place, by that struct's fields (D-051). tygo otherwise emits an
// embedded type as a *named property* (`Base: Base;`), but the JSON Schema
// generator — and Go's own encoding/json — *inline* an embedded struct's
// fields. Flattening makes the TypeScript artifact agree with the schema and
// with the wire format the UI actually deserializes.
func typeDeclSourceForFile(goSource string, imported importedTypes, flatten, normalizeTags, rewriteJSONString bool) (string, error) {
	src := goSource
	// A bare fragment (no package clause) is not a valid Go file; wrap it so the
	// parser accepts it. A real package clause is left in place and dropped below.
	if !hasPackageClause(src) {
		src = "package contracts\n\n" + src
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "contracts.go", src, parser.ParseComments)
	if err != nil {
		return "", fmt.Errorf("parse contract source: %w", err)
	}

	if normalizeTags {
		if err := normalizeNamedJSONTags(file); err != nil {
			return "", err
		}
	}
	promotedDocs := map[string]map[string]string{}
	if flatten {
		promotedDocs, err = flattenEmbeddedStructs(file)
		if err != nil {
			return "", err
		}
	}
	nameTaggedAnonymousJSONStringFields(file)
	if err := rewriteImportedTypes(file, imported); err != nil {
		return "", err
	}
	if rewriteJSONString {
		if err := rewriteJSONStringFields(file); err != nil {
			return "", err
		}
	}

	var out bytes.Buffer
	pcfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue // skip funcs
		}
		if gen.Tok != token.TYPE && gen.Tok != token.CONST {
			continue // skip imports and vars
		}
		if out.Len() > 0 {
			out.WriteString("\n\n")
		}
		if err := pcfg.Fprint(&out, fset, gen); err != nil {
			return "", fmt.Errorf("render declaration: %w", err)
		}
	}
	return injectPromotedComments(out.String(), promotedDocs), nil
}

// nameTaggedAnonymousJSONStringFields adapts explicitly string-tagged embedded
// scalars for tygo, which otherwise omits every anonymous non-struct field. The
// JSON tag still owns the wire property name; the synthetic AST name preserves
// the embedded type's Go field identity through imported-type rewriting.
func nameTaggedAnonymousJSONStringFields(file *ast.File) {
	ast.Inspect(file, func(node ast.Node) bool {
		field, ok := node.(*ast.Field)
		if !ok || len(field.Names) != 0 {
			return true
		}
		tag, ok := fieldJSONTag(field)
		if !ok || !containsTagOption(tag, "string") {
			return true
		}
		if name := anonymousFieldTypeName(field.Type); name != "" {
			field.Names = []*ast.Ident{ast.NewIdent(name)}
		}
		return true
	})
}

func anonymousFieldTypeName(expr ast.Expr) string {
	if pointer, ok := expr.(*ast.StarExpr); ok {
		expr = pointer.X
	}
	switch typ := expr.(type) {
	case *ast.Ident:
		return typ.Name
	case *ast.SelectorExpr:
		return typ.Sel.Name
	default:
		return ""
	}
}

// importedTypes carries file-scoped imported type identities. The rewriter
// expands them to standalone TypeScript wire shapes; byte slices are strings.
type importedTypes struct {
	byteElements map[string]bool
	byteSlices   map[string]bool
	types        map[string]types.Type
	expander     *wireTypeExpander
	resolved     bool
}

func rewriteImportedTypes(file *ast.File, imported importedTypes) error {
	if !imported.resolved {
		for _, imp := range file.Imports {
			if imp.Name != nil && imp.Name.Name == "." {
				return fmt.Errorf("cannot safely resolve dot-imported contract types from source alone; use TypeScriptForDir")
			}
		}
	}
	if err := rejectUnresolvedValueSelectors(file); err != nil {
		return err
	}
	byteTypes := map[string]bool{"byte": true, "uint8": true}
	for name := range imported.byteElements {
		byteTypes[name] = true
	}
	byteSliceTypes := make(map[string]bool, len(imported.byteSlices))
	for name := range imported.byteSlices {
		byteSliceTypes[name] = true
	}
	// Resolve local alias chains to their uint8 underlying type before walking
	// fields, and local named slices whose element resolves to uint8. This mirrors
	// encoding/json's byte-slice special case, which follows underlying kinds
	// rather than source spelling.
	changed := true
	for changed {
		changed = false
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				name := typeSpec.Name.Name
				if !byteTypes[name] && byteTypes[exprTypeName(typeSpec.Type)] {
					byteTypes[name] = true
					changed = true
				}
				if !byteSliceTypes[name] && isByteSliceExpr(typeSpec.Type, byteTypes, byteSliceTypes) {
					byteSliceTypes[name] = true
					changed = true
				}
			}
		}
	}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if ok {
				var err error
				typeSpec.Type, err = rewriteWireExpr(typeSpec.Type, byteTypes, byteSliceTypes, imported.types, imported.expander)
				if err != nil {
					return err
				}
			}
		}
	}
	if imported.expander != nil {
		file.Decls = append(file.Decls, imported.expander.takeDeclarations()...)
	}
	return nil
}

// rejectUnresolvedValueSelectors prevents retained constants from silently
// degrading package-qualified values to tygo's `any /* pkg.Value */`. Imports
// are stripped before conversion, and this declaration conversion cannot prove
// the wire value of an imported constant.
func rejectUnresolvedValueSelectors(file *ast.File) error {
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}
		var selector *ast.SelectorExpr
		ast.Inspect(gen, func(node ast.Node) bool {
			if selector != nil {
				return false
			}
			if candidate, ok := node.(*ast.SelectorExpr); ok {
				selector = candidate
				return false
			}
			return true
		})
		if selector != nil {
			return fmt.Errorf("cannot safely resolve imported value %s in retained const declaration", renderExpr(selector))
		}
	}
	return nil
}

func isByteSliceExpr(expr ast.Expr, byteTypes, byteSliceTypes map[string]bool) bool {
	if byteSliceTypes[exprTypeName(expr)] {
		return true
	}
	array, ok := expr.(*ast.ArrayType)
	return ok && array.Len == nil && byteTypes[exprTypeName(array.Elt)]
}

func rewriteWireExpr(expr ast.Expr, byteTypes, byteSliceTypes map[string]bool, imported map[string]types.Type, expander *wireTypeExpander) (ast.Expr, error) {
	if byteSliceTypes[exprTypeName(expr)] {
		return ast.NewIdent("string"), nil
	}
	if typ := imported[exprTypeName(expr)]; typ != nil {
		nodes := 0
		return wireExprForType(typ, make(map[types.Type]bool), 0, &nodes, expander)
	}
	switch e := expr.(type) {
	case *ast.ArrayType:
		if e.Len == nil && byteTypes[exprTypeName(e.Elt)] {
			return ast.NewIdent("string"), nil
		}
		var err error
		e.Elt, err = rewriteWireExpr(e.Elt, byteTypes, byteSliceTypes, imported, expander)
		if err != nil {
			return nil, err
		}
	case *ast.StarExpr:
		var err error
		e.X, err = rewriteWireExpr(e.X, byteTypes, byteSliceTypes, imported, expander)
		if err != nil {
			return nil, err
		}
	case *ast.MapType:
		var err error
		e.Key, err = rewriteWireExpr(e.Key, byteTypes, byteSliceTypes, imported, expander)
		if err != nil {
			return nil, err
		}
		e.Value, err = rewriteWireExpr(e.Value, byteTypes, byteSliceTypes, imported, expander)
		if err != nil {
			return nil, err
		}
	case *ast.SelectorExpr:
		return nil, fmt.Errorf("cannot safely resolve imported type %s from source alone; use TypeScriptForDir", renderExpr(e))
	case *ast.StructType:
		for _, field := range e.Fields.List {
			if tag, ok := fieldJSONTag(field); ok && tag == "-" {
				continue
			}
			if len(field.Names) == 0 && expander != nil {
				base := field.Type
				pointer := false
				if star, ok := base.(*ast.StarExpr); ok {
					base = star.X
					pointer = true
				}
				if named := importedNamedStruct(imported[exprTypeName(base)]); named != nil {
					if hasCustomJSONEncoding(named) {
						return nil, fmt.Errorf("imported type %s has custom JSON encoding without a schema wire-shape mapping", named.String())
					}
					ref, err := expander.reference(named, 0, new(int))
					if err != nil {
						return nil, err
					}
					if pointer {
						field.Type = &ast.StarExpr{X: ref}
					} else {
						field.Type = ref
					}
					continue
				}
			}
			var err error
			field.Type, err = rewriteWireExpr(field.Type, byteTypes, byteSliceTypes, imported, expander)
			if err != nil {
				return nil, err
			}
		}
	case *ast.ChanType:
		return ast.NewIdent("any"), nil
	case *ast.FuncType:
		return ast.NewIdent("any"), nil
	case *ast.InterfaceType:
		return ast.NewIdent("any"), nil
	}
	return expr, nil
}

func importedNamedStruct(t types.Type) *types.Named {
	if alias, ok := t.(*types.Alias); ok {
		t = types.Unalias(alias)
	}
	named, ok := t.(*types.Named)
	if !ok {
		return nil
	}
	if _, ok := named.Underlying().(*types.Struct); !ok {
		return nil
	}
	return named
}

func wireExprForType(t types.Type, path map[types.Type]bool, depth int, nodes *int, expander *wireTypeExpander) (ast.Expr, error) {
	if depth > maxGenerationDepth {
		return nil, fmt.Errorf("imported type graph exceeds depth %d", maxGenerationDepth)
	}
	*nodes++
	if *nodes > maxGenerationNodes {
		return nil, fmt.Errorf("imported type graph exceeds %d nodes", maxGenerationNodes)
	}
	if named, ok := t.(*types.Named); ok {
		if obj := named.Obj(); obj != nil && obj.Pkg() != nil {
			switch obj.Pkg().Path() + "." + obj.Name() {
			case "time.Time", "log/slog.Level":
				return ast.NewIdent("string"), nil
			case "encoding/json.RawMessage":
				return ast.NewIdent("any"), nil
			}
		}
		if hasCustomJSONEncoding(named) {
			return nil, fmt.Errorf("imported type %s has custom JSON encoding without a schema wire-shape mapping", named.String())
		}
		if expander != nil && recursiveImportedType(named, make(map[types.Type]bool), make(map[types.Type]bool), 0) {
			return expander.reference(named, depth, nodes)
		}
		if path[named] {
			if expander != nil {
				return expander.reference(named, depth, nodes)
			}
			return nil, fmt.Errorf("recursive imported type %s requires a named TypeScript declaration", named.String())
		}
		next := cloneTypePath(path)
		next[named] = true
		return wireExprForType(named.Underlying(), next, depth+1, nodes, expander)
	}
	if alias, ok := t.(*types.Alias); ok {
		return wireExprForType(types.Unalias(alias), path, depth+1, nodes, expander)
	}
	switch typ := t.(type) {
	case *types.Basic:
		switch typ.Kind() {
		case types.Bool:
			return ast.NewIdent("bool"), nil
		case types.String:
			return ast.NewIdent("string"), nil
		case types.UnsafePointer, types.UntypedNil, types.Invalid:
			return ast.NewIdent("any"), nil
		default:
			return ast.NewIdent(typ.Name()), nil
		}
	case *types.Pointer:
		elem, err := wireExprForType(typ.Elem(), path, depth+1, nodes, expander)
		if err != nil {
			return nil, err
		}
		return &ast.StarExpr{X: elem}, nil
	case *types.Slice:
		if isUint8Type(typ.Elem()) {
			return ast.NewIdent("string"), nil
		}
		elem, err := wireExprForType(typ.Elem(), path, depth+1, nodes, expander)
		if err != nil {
			return nil, err
		}
		return &ast.ArrayType{Elt: elem}, nil
	case *types.Array:
		elem, err := wireExprForType(typ.Elem(), path, depth+1, nodes, expander)
		if err != nil {
			return nil, err
		}
		return &ast.ArrayType{Len: &ast.BasicLit{Kind: token.INT, Value: strconv.FormatInt(typ.Len(), 10)}, Elt: elem}, nil
	case *types.Map:
		key, err := wireExprForType(typ.Key(), path, depth+1, nodes, expander)
		if err != nil {
			return nil, err
		}
		value, err := wireExprForType(typ.Elem(), path, depth+1, nodes, expander)
		if err != nil {
			return nil, err
		}
		return &ast.MapType{Key: key, Value: value}, nil
	case *types.Struct:
		fields, err := externalStructFields(typ, path, depth+1, nodes, expander)
		if err != nil {
			return nil, err
		}
		return &ast.StructType{Fields: &ast.FieldList{List: fields}}, nil
	default:
		return ast.NewIdent("any"), nil
	}
}

func hasCustomJSONEncoding(named *types.Named) bool {
	return types.Implements(named, jsonMarshalerInterface()) ||
		types.Implements(types.NewPointer(named), jsonMarshalerInterface()) ||
		types.Implements(named, textMarshalerInterface()) ||
		types.Implements(types.NewPointer(named), textMarshalerInterface())
}

func jsonMarshalerInterface() *types.Interface {
	results := types.NewTuple(
		types.NewVar(token.NoPos, nil, "", types.NewSlice(types.Typ[types.Byte])),
		types.NewVar(token.NoPos, nil, "", types.Universe.Lookup("error").Type()),
	)
	method := types.NewFunc(token.NoPos, nil, "MarshalJSON", types.NewSignatureType(nil, nil, nil, nil, results, false))
	return types.NewInterfaceType([]*types.Func{method}, nil).Complete()
}

func textMarshalerInterface() *types.Interface {
	results := types.NewTuple(
		types.NewVar(token.NoPos, nil, "", types.NewSlice(types.Typ[types.Byte])),
		types.NewVar(token.NoPos, nil, "", types.Universe.Lookup("error").Type()),
	)
	method := types.NewFunc(token.NoPos, nil, "MarshalText", types.NewSignatureType(nil, nil, nil, nil, results, false))
	return types.NewInterfaceType([]*types.Func{method}, nil).Complete()
}

func rejectLocalCustomJSONEncoding(dir, filename string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes,
		Dir:  dir,
		Env:  append(os.Environ(), "GOPROXY=off", "GOSUMDB=off"),
	}
	entry, err := filepath.Abs(filepath.Join(dir, filename))
	if err != nil {
		return fmt.Errorf("resolve canonical contract source: %w", err)
	}
	loaded, err := packages.Load(cfg, "file="+entry)
	if err == nil && len(loaded) == 1 && len(loaded[0].Errors) > 0 {
		err = errors.New(loaded[0].Errors[0].Error())
	}
	if err == nil && (len(loaded) != 1 || loaded[0].Types == nil) {
		err = fmt.Errorf("loader returned %d packages", len(loaded))
	}
	if err != nil {
		return fmt.Errorf("load canonical contract package offline: %w", err)
	}
	pkg := loaded[0]
	for _, name := range pkg.Types.Scope().Names() {
		obj, ok := pkg.Types.Scope().Lookup(name).(*types.TypeName)
		if !ok {
			continue
		}
		named, ok := types.Unalias(obj.Type()).(*types.Named)
		if !ok || supportedWireType(named) || !hasCustomJSONEncoding(named) {
			continue
		}
		return fmt.Errorf("canonical contract type %s has custom JSON encoding without a schema wire-shape mapping", named.String())
	}
	return nil
}

func supportedWireType(named *types.Named) bool {
	if named == nil || named.Obj() == nil || named.Obj().Pkg() == nil {
		return false
	}
	switch named.Obj().Pkg().Path() + "." + named.Obj().Name() {
	case "time.Time", "log/slog.Level", "encoding/json.RawMessage":
		return true
	default:
		return false
	}
}

type wireTypeExpander struct {
	names    map[*types.Named]string
	pending  []ast.Decl
	emitted  map[*types.Named]bool
	building map[*types.Named]bool
}

func newWireTypeExpander() *wireTypeExpander {
	return &wireTypeExpander{
		names:    make(map[*types.Named]string),
		emitted:  make(map[*types.Named]bool),
		building: make(map[*types.Named]bool),
	}
}

func (e *wireTypeExpander) reference(named *types.Named, depth int, nodes *int) (ast.Expr, error) {
	name := e.name(named)
	if e.emitted[named] || e.building[named] {
		return ast.NewIdent(name), nil
	}
	e.building[named] = true
	body, err := wireExprForType(named.Underlying(), map[types.Type]bool{named: true}, depth+1, nodes, e)
	delete(e.building, named)
	if err != nil {
		return nil, err
	}
	e.pending = append(e.pending, &ast.GenDecl{Tok: token.TYPE, Specs: []ast.Spec{
		&ast.TypeSpec{Name: ast.NewIdent(name), Type: body},
	}})
	e.emitted[named] = true
	return ast.NewIdent(name), nil
}

func (e *wireTypeExpander) name(named *types.Named) string {
	if name := e.names[named]; name != "" {
		return name
	}
	qualified := named.String()
	h := fnv.New32a()
	_, _ = h.Write([]byte(qualified))
	name := fmt.Sprintf("DockyardImported%s_%08x", named.Obj().Name(), h.Sum32())
	e.names[named] = name
	return name
}

func (e *wireTypeExpander) takeDeclarations() []ast.Decl {
	out := e.pending
	e.pending = nil
	return out
}

func recursiveImportedType(t types.Type, path, done map[types.Type]bool, depth int) bool {
	if depth > maxGenerationDepth {
		return true
	}
	if alias, ok := t.(*types.Alias); ok {
		t = types.Unalias(alias)
	}
	if named, ok := t.(*types.Named); ok {
		if path[named] {
			return true
		}
		if done[named] {
			return false
		}
		next := cloneTypePath(path)
		next[named] = true
		if recursiveImportedType(named.Underlying(), next, done, depth+1) {
			return true
		}
		done[named] = true
		return false
	}
	switch typ := t.(type) {
	case *types.Pointer:
		return recursiveImportedType(typ.Elem(), path, done, depth+1)
	case *types.Slice:
		return recursiveImportedType(typ.Elem(), path, done, depth+1)
	case *types.Array:
		return recursiveImportedType(typ.Elem(), path, done, depth+1)
	case *types.Map:
		return recursiveImportedType(typ.Key(), path, done, depth+1) || recursiveImportedType(typ.Elem(), path, done, depth+1)
	case *types.Struct:
		for i := 0; i < typ.NumFields(); i++ {
			field := typ.Field(i)
			if reflect.StructTag(typ.Tag(i)).Get("json") == "-" || (!field.Exported() && !field.Anonymous()) {
				continue
			}
			if recursiveImportedType(field.Type(), path, done, depth+1) {
				return true
			}
		}
	}
	return false
}

type externalField struct {
	field    *types.Var
	tag      string
	name     string
	depth    int
	tagged   bool
	optional bool
	order    int
}

func externalStructFields(root *types.Struct, path map[types.Type]bool, depth int, nodes *int, expander *wireTypeExpander) ([]*ast.Field, error) {
	order := 0
	candidates, err := externalFieldCandidates(root, path, depth, false, nodes, &order)
	if err != nil {
		return nil, err
	}
	byName := make(map[string][]externalField)
	for _, candidate := range candidates {
		byName[candidate.name] = append(byName[candidate.name], candidate)
	}
	selected := make([]externalField, 0, len(byName))
	for _, sameName := range byName {
		minDepth := sameName[0].depth
		for _, candidate := range sameName[1:] {
			if candidate.depth < minDepth {
				minDepth = candidate.depth
			}
		}
		var dominant []externalField
		for _, candidate := range sameName {
			if candidate.depth == minDepth {
				dominant = append(dominant, candidate)
			}
		}
		hasTagged := false
		for _, candidate := range dominant {
			hasTagged = hasTagged || candidate.tagged
		}
		if hasTagged {
			filtered := dominant[:0]
			for _, candidate := range dominant {
				if candidate.tagged {
					filtered = append(filtered, candidate)
				}
			}
			dominant = filtered
		}
		if len(dominant) == 1 {
			selected = append(selected, dominant[0])
		}
	}
	sort.Slice(selected, func(i, j int) bool { return selected[i].order < selected[j].order })
	out := make([]*ast.Field, 0, len(selected))
	for _, candidate := range selected {
		typ, err := wireExprForType(candidate.field.Type(), path, depth+1, nodes, expander)
		if err != nil {
			return nil, err
		}
		tag := candidate.tag
		if jsonTag, ok := reflect.StructTag(tag).Lookup("json"); ok {
			if normalized, changed := normalizeJSONTagValue(jsonTag); changed {
				tag = replaceJSONStructTag(tag, normalized)
			}
		}
		if candidate.optional && !containsTagOption(reflect.StructTag(tag).Get("json"), "omitempty") && !containsTagOption(reflect.StructTag(tag).Get("json"), "omitzero") {
			jsonTag := reflect.StructTag(tag).Get("json")
			if jsonTag == "" {
				jsonTag = candidate.name
			}
			tag = replaceJSONStructTag(tag, jsonTag+",omitempty")
		}
		field := &ast.Field{Names: []*ast.Ident{ast.NewIdent(candidate.field.Name())}, Type: typ}
		if tag != "" {
			field.Tag = &ast.BasicLit{Kind: token.STRING, Value: "`" + tag + "`"}
		}
		out = append(out, field)
	}
	return out, nil
}

func externalFieldCandidates(root *types.Struct, path map[types.Type]bool, depth int, optionalAncestor bool, nodes, order *int) ([]externalField, error) {
	if depth > maxGenerationDepth {
		return nil, fmt.Errorf("imported struct field graph exceeds depth %d", maxGenerationDepth)
	}
	var out []externalField
	for i := 0; i < root.NumFields(); i++ {
		*nodes++
		if *nodes > maxGenerationNodes {
			return nil, fmt.Errorf("imported type graph exceeds %d nodes", maxGenerationNodes)
		}
		field := root.Field(i)
		tag := root.Tag(i)
		jsonTag, hasTag := reflect.StructTag(tag).Lookup("json")
		name, _, _ := strings.Cut(jsonTag, ",")
		if jsonTag == "-" || (!field.Exported() && !field.Anonymous()) {
			continue
		}
		tagged := hasTag && name != "" && validJSONTag(name)
		fieldType := field.Type()
		pointerEmbedded := field.Anonymous()
		if pointer, ok := fieldType.(*types.Pointer); ok {
			fieldType = pointer.Elem()
		} else {
			pointerEmbedded = false
		}
		underlying := fieldType.Underlying()
		if field.Anonymous() && !tagged {
			if embedded, ok := underlying.(*types.Struct); ok && !path[fieldType] {
				next := cloneTypePath(path)
				next[fieldType] = true
				promoted, err := externalFieldCandidates(embedded, next, depth+1, optionalAncestor || pointerEmbedded, nodes, order)
				if err != nil {
					return nil, err
				}
				out = append(out, promoted...)
				continue
			}
		}
		if !field.Exported() {
			continue
		}
		if !tagged {
			name = field.Name()
		}
		out = append(out, externalField{field: field, tag: tag, name: name, depth: depth, tagged: tagged, optional: optionalAncestor, order: *order})
		*order++
	}
	return out, nil
}

func cloneTypePath(path map[types.Type]bool) map[types.Type]bool {
	out := make(map[types.Type]bool, len(path)+1)
	for typ := range path {
		out[typ] = true
	}
	return out
}

func replaceJSONStructTag(tag, value string) string {
	replacement := "json:" + strconv.Quote(value)
	if match := jsonStructTagRE.FindStringIndex(tag); match != nil {
		prefix := tag[match[0]:match[1]]
		leading := prefix[:len(prefix)-len(strings.TrimLeft(prefix, " \t"))]
		return tag[:match[0]] + leading + replacement + tag[match[1]:]
	}
	if tag == "" {
		return replacement
	}
	return tag + " " + replacement
}

func exprTypeName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		if pkg, ok := e.X.(*ast.Ident); ok {
			return pkg.Name + "." + e.Sel.Name
		}
	}
	return ""
}

// importedTypeResolver asks the Go loader for imported type identities instead
// of inferring them from source paths. GOPROXY=off and GOSUMDB=off make
// resolution strictly offline: packages may come from the main module,
// replacements, the standard library, or existing caches, but generation never
// downloads code.
type importedTypeResolver struct {
	dir      string
	loaded   map[string]*packages.Package
	loadErrs map[string]error
	nodes    int
	expander *wireTypeExpander
}

func newImportedTypeResolver(dir string) *importedTypeResolver {
	return &importedTypeResolver{
		dir:      dir,
		loaded:   make(map[string]*packages.Package),
		loadErrs: make(map[string]error),
		expander: newWireTypeExpander(),
	}
}

func (r *importedTypeResolver) importedTypesForFile(filename string, raw []byte) (importedTypes, error) {
	file, err := parser.ParseFile(token.NewFileSet(), filename, raw, 0)
	if err != nil {
		return importedTypes{}, fmt.Errorf("parse imports: %w", err)
	}
	if len(file.Imports) == 0 || !containsImportedTypeReference(file) {
		return importedTypes{}, nil
	}
	out := importedTypes{byteElements: make(map[string]bool), byteSlices: make(map[string]bool), types: make(map[string]types.Type), expander: r.expander, resolved: true}
	for _, imp := range file.Imports {
		importPath, err := strconv.Unquote(imp.Path.Value)
		if err != nil {
			return importedTypes{}, fmt.Errorf("invalid import path %s: %w", imp.Path.Value, err)
		}
		pkg, err := r.load(importPath)
		if err != nil {
			return importedTypes{}, err
		}
		alias := pkg.Name
		if imp.Name != nil {
			alias = imp.Name.Name
		}
		if alias == "_" || alias == "" {
			continue
		}
		for _, name := range pkg.Types.Scope().Names() {
			r.nodes++
			if r.nodes > maxGenerationNodes {
				return importedTypes{}, fmt.Errorf("imported type resolution exceeds %d declarations", maxGenerationNodes)
			}
			obj, ok := pkg.Types.Scope().Lookup(name).(*types.TypeName)
			if !ok {
				continue
			}
			qualified := name
			if alias != "." {
				qualified = alias + "." + name
			}
			out.types[qualified] = obj.Type()
			switch {
			case isUint8Type(obj.Type()):
				out.byteElements[qualified] = true
			case isByteSliceType(obj.Type()):
				out.byteSlices[qualified] = true
			}
		}
	}
	return out, nil
}

func (r *importedTypeResolver) load(importPath string) (*packages.Package, error) {
	if pkg := r.loaded[importPath]; pkg != nil {
		return pkg, nil
	}
	if err := r.loadErrs[importPath]; err != nil {
		return nil, err
	}
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes,
		Dir:  r.dir,
		Env:  append(os.Environ(), "GOPROXY=off", "GOSUMDB=off"),
	}
	loaded, err := packages.Load(cfg, importPath)
	if err == nil && len(loaded) == 1 && len(loaded[0].Errors) > 0 {
		err = errors.New(loaded[0].Errors[0].Error())
	}
	if err == nil && (len(loaded) != 1 || loaded[0].Types == nil) {
		err = fmt.Errorf("loader returned %d packages", len(loaded))
	}
	if err != nil {
		wrapped := fmt.Errorf("load import %s offline: %w", importPath, err)
		r.loadErrs[importPath] = wrapped
		return nil, wrapped
	}
	r.loaded[importPath] = loaded[0]
	return loaded[0], nil
}

func containsImportedTypeReference(file *ast.File) bool {
	found := false
	for _, imp := range file.Imports {
		if imp.Name != nil && imp.Name.Name == "." {
			return true
		}
	}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		ast.Inspect(gen, func(node ast.Node) bool {
			if _, ok := node.(*ast.SelectorExpr); ok {
				found = true
				return false
			}
			return !found
		})
		if found {
			break
		}
	}
	return found
}

func isUint8Type(t types.Type) bool {
	basic, ok := t.Underlying().(*types.Basic)
	return ok && basic.Kind() == types.Uint8
}

func isByteSliceType(t types.Type) bool {
	slice, ok := t.Underlying().(*types.Slice)
	return ok && isUint8Type(slice.Elem())
}

// flattenEmbeddedStructs rewrites every struct type declared in file so that
// each embedded (anonymous) field referencing another locally declared struct
// is replaced by that struct's own fields (D-051).
//
// The rewrite matches Go's encoding/json semantics:
//   - An embedded struct's fields are promoted into the embedding struct.
//   - A field of the outer struct shadows a promoted field of the same JSON
//     name ("outer wins"); the promoted duplicate is dropped.
//   - Promotion is transitive: an embedded struct that itself embeds another is
//     flattened first, so its already-promoted fields carry through.
//
// This pass flattens structs declared in the same source. Imported types are
// resolved and expanded later by rewriteImportedTypes, which applies the same
// dominance rules from go/types metadata.
func flattenEmbeddedStructs(file *ast.File) (map[string]map[string]string, error) {
	structs := make(map[string]*ast.StructType)
	original := make(map[string][]*ast.Field)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			if st, ok := ts.Type.(*ast.StructType); ok {
				structs[ts.Name.Name] = st
				original[ts.Name.Name] = append([]*ast.Field(nil), st.Fields.List...)
			}
		}
	}
	nodes := 0
	resolved := make(map[string][]*ast.Field, len(structs))
	promotedDocs := make(map[string]map[string]string)
	for name := range structs {
		fields, docs, err := flattenStruct(name, original, &nodes)
		if err != nil {
			return nil, err
		}
		resolved[name] = fields
		if len(docs) > 0 {
			promotedDocs[name] = docs
		}
	}
	for name, fields := range resolved {
		structs[name].Fields.List = fields
	}
	return promotedDocs, nil
}

type tsFieldCandidate struct {
	field    *ast.Field
	name     string
	depth    int
	tagged   bool
	optional bool
	order    int
}

// flattenStruct applies encoding/json's breadth/dominance rules rather than a
// textual "last field wins" rewrite. Pointer embedding makes promoted fields
// optional because a nil ancestor omits the entire promoted subtree.
func flattenStruct(name string, structs map[string][]*ast.Field, nodes *int) ([]*ast.Field, map[string]string, error) {
	order := 0
	candidates, err := embeddedFieldCandidates(name, structs, make(map[string]bool), 0, false, nodes, &order)
	if err != nil {
		return nil, nil, err
	}
	byName := make(map[string][]tsFieldCandidate)
	var anonymous []tsFieldCandidate
	for _, candidate := range candidates {
		if candidate.name == "" {
			anonymous = append(anonymous, candidate)
		} else {
			byName[candidate.name] = append(byName[candidate.name], candidate)
		}
	}
	selected := append([]tsFieldCandidate(nil), anonymous...)
	for _, sameName := range byName {
		minDepth := sameName[0].depth
		for _, candidate := range sameName[1:] {
			if candidate.depth < minDepth {
				minDepth = candidate.depth
			}
		}
		var dominant []tsFieldCandidate
		for _, candidate := range sameName {
			if candidate.depth == minDepth {
				dominant = append(dominant, candidate)
			}
		}
		hasTagged := false
		for _, candidate := range dominant {
			hasTagged = hasTagged || candidate.tagged
		}
		if hasTagged {
			filtered := dominant[:0]
			for _, candidate := range dominant {
				if candidate.tagged {
					filtered = append(filtered, candidate)
				}
			}
			dominant = filtered
		}
		if len(dominant) == 1 {
			selected = append(selected, dominant[0])
		}
	}
	sort.Slice(selected, func(i, j int) bool { return selected[i].order < selected[j].order })
	out := make([]*ast.Field, 0, len(selected))
	docs := make(map[string]string)
	for _, candidate := range selected {
		field := cloneASTField(candidate.field)
		if candidate.optional {
			ensureJSONTagOption(field, "omitempty")
		}
		out = append(out, field)
		if candidate.depth > 0 && field.Doc != nil && len(field.Names) == 1 {
			docs[field.Names[0].Name] = field.Doc.Text()
		}
	}
	return out, docs, nil
}

func embeddedFieldCandidates(name string, structs map[string][]*ast.Field, path map[string]bool, depth int, optionalAncestor bool, nodes, order *int) ([]tsFieldCandidate, error) {
	if depth > maxGenerationDepth {
		return nil, fmt.Errorf("embedded TypeScript field graph exceeds depth %d", maxGenerationDepth)
	}
	*nodes++
	if *nodes > maxGenerationNodes {
		return nil, fmt.Errorf("embedded TypeScript field graph exceeds %d nodes", maxGenerationNodes)
	}
	if path[name] {
		return nil, nil
	}
	fields, ok := structs[name]
	if !ok {
		return nil, nil
	}
	nextPath := make(map[string]bool, len(path)+1)
	for item := range path {
		nextPath[item] = true
	}
	nextPath[name] = true
	candidates := make([]tsFieldCandidate, 0, len(fields))
	for _, f := range fields {
		embeddedName, ok := embeddedStructName(f)
		if ok {
			if _, isLocalStruct := structs[embeddedName]; isLocalStruct {
				promoted, err := embeddedFieldCandidates(embeddedName, structs, nextPath, depth+1, optionalAncestor || embeddedFieldIsPointer(f), nodes, order)
				if err != nil {
					return nil, err
				}
				candidates = append(candidates, promoted...)
				continue
			}
		}
		ordinaryFields := []*ast.Field{f}
		if len(f.Names) > 1 {
			ordinaryFields = make([]*ast.Field, 0, len(f.Names))
			for _, fieldName := range f.Names {
				clone := cloneASTField(f)
				clone.Names = []*ast.Ident{fieldName}
				ordinaryFields = append(ordinaryFields, clone)
			}
		}
		for _, ordinary := range ordinaryFields {
			key, tagged, ignored := fieldJSONIdentity(ordinary)
			if ignored {
				continue
			}
			candidates = append(candidates, tsFieldCandidate{field: cloneASTField(ordinary), name: key, depth: depth, tagged: tagged, optional: optionalAncestor, order: *order})
			*order++
		}
		if len(candidates) > maxGenerationNodes {
			return nil, fmt.Errorf("embedded TypeScript field graph exceeds %d nodes", maxGenerationNodes)
		}
	}
	return candidates, nil
}

func embeddedFieldIsPointer(f *ast.Field) bool {
	_, ok := f.Type.(*ast.StarExpr)
	return ok
}

func cloneASTField(f *ast.Field) *ast.Field {
	clone := *f
	clone.Names = append([]*ast.Ident(nil), f.Names...)
	clone.Doc = cloneCommentGroup(f.Doc)
	clone.Comment = cloneCommentGroup(f.Comment)
	if f.Tag != nil {
		tag := *f.Tag
		clone.Tag = &tag
	}
	return &clone
}

func cloneCommentGroup(group *ast.CommentGroup) *ast.CommentGroup {
	if group == nil {
		return nil
	}
	clone := &ast.CommentGroup{List: make([]*ast.Comment, len(group.List))}
	for i, comment := range group.List {
		clonedComment := *comment
		clone.List[i] = &clonedComment
	}
	return clone
}

func generatedGoSource(raw []byte) bool {
	file, err := parser.ParseFile(token.NewFileSet(), "generated.go", raw, parser.PackageClauseOnly|parser.ParseComments)
	return err == nil && ast.IsGenerated(file)
}

func injectPromotedComments(source string, docs map[string]map[string]string) string {
	if len(docs) == 0 {
		return source
	}
	lines := strings.Split(source, "\n")
	out := make([]string, 0, len(lines))
	current := ""
	depth := 0
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if current == "" && strings.HasPrefix(trimmed, "type ") && strings.Contains(trimmed, " struct {") {
			fields := strings.Fields(trimmed)
			if len(fields) >= 3 {
				name := fields[1]
				if i := strings.IndexByte(name, '['); i >= 0 {
					name = name[:i]
				}
				if docs[name] != nil {
					current = name
					depth = 0
				}
			}
		} else if current != "" && depth == 1 {
			for field, text := range docs[current] {
				if strings.HasPrefix(trimmed, field+" ") || strings.HasPrefix(trimmed, field+"\t") {
					indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
					for _, commentLine := range strings.Split(strings.TrimSuffix(text, "\n"), "\n") {
						if commentLine == "" {
							out = append(out, indent+"//")
						} else {
							out = append(out, indent+"// "+commentLine)
						}
					}
					break
				}
			}
		}
		out = append(out, line)
		if current != "" {
			depth += braceDelta(line)
			if depth <= 0 {
				current = ""
			}
		}
	}
	return strings.Join(out, "\n")
}

func fieldJSONIdentity(f *ast.Field) (name string, tagged, ignored bool) {
	if len(f.Names) == 0 {
		if tag, ok := fieldJSONTag(f); ok {
			name, _, _ = strings.Cut(tag, ",")
			if tag == "-" {
				return "", false, true
			}
			if name != "" && validJSONTag(name) {
				return name, true, false
			}
		}
		return "", false, false
	}
	name = f.Names[0].Name
	tag, ok := fieldJSONTag(f)
	if !ok || tag == "" {
		return name, false, false
	}
	tagName, _, _ := strings.Cut(tag, ",")
	if tag == "-" {
		return "", false, true
	}
	if tagName == "" || !validJSONTag(tagName) {
		return name, false, false
	}
	return tagName, true, false
}

func fieldJSONTag(f *ast.Field) (string, bool) {
	if f.Tag == nil {
		return "", false
	}
	body, err := strconv.Unquote(f.Tag.Value)
	if err != nil {
		return "", false
	}
	return reflect.StructTag(body).Lookup("json")
}

func ensureJSONTagOption(f *ast.Field, option string) {
	tag, ok := fieldJSONTag(f)
	if !ok {
		setJSONTag(f, ","+option)
		return
	}
	parts := strings.Split(tag, ",")
	for _, existing := range parts[1:] {
		if existing == option || (option == "omitempty" && existing == "omitzero") {
			return
		}
	}
	setJSONTag(f, tag+","+option)
}

func normalizeNamedJSONTags(file *ast.File) error {
	var normalizeErr error
	ast.Inspect(file, func(node ast.Node) bool {
		if normalizeErr != nil {
			return false
		}
		field, ok := node.(*ast.Field)
		if !ok {
			return true
		}
		if field.Tag != nil {
			body, err := strconv.Unquote(field.Tag.Value)
			if err != nil {
				normalizeErr = fmt.Errorf("invalid struct tag: %w", err)
				return false
			}
			if _, err := structtag.Parse(body); err != nil {
				normalizeErr = fmt.Errorf("invalid struct tag: %w", err)
				return false
			}
		}
		tag, ok := fieldJSONTag(field)
		if !ok {
			return true
		}
		if normalized, changed := normalizeJSONTagValue(tag); changed {
			setJSONTag(field, normalized)
		}
		return true
	})
	return normalizeErr
}

type namedJSONType struct {
	expr  ast.Expr
	alias bool
}

func rewriteJSONStringFields(file *ast.File) error {
	named := make(map[string]namedJSONType)
	declarations := 0
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			if typeSpec, ok := spec.(*ast.TypeSpec); ok {
				declarations++
				if declarations > maxGenerationNodes {
					return fmt.Errorf("json ,string declaration index exceeds %d types", maxGenerationNodes)
				}
				named[typeSpec.Name.Name] = namedJSONType{expr: typeSpec.Type, alias: typeSpec.Assign.IsValid()}
			}
		}
	}
	var rewriteErr error
	ast.Inspect(file, func(node ast.Node) bool {
		if rewriteErr != nil {
			return false
		}
		field, ok := node.(*ast.Field)
		if !ok {
			return true
		}
		tag, ok := fieldJSONTag(field)
		if !ok || !containsTagOption(tag, "string") {
			return true
		}
		supported, nullable := supportsJSONStringExpr(field.Type, named, make(map[string]bool), true, 0)
		if !supported {
			rewriteErr = fmt.Errorf("json ,string uses unsupported field type %s", renderExpr(field.Type))
			return false
		}
		field.Type = ast.NewIdent("string")
		if nullable {
			if err := setStructTag(field, &structtag.Tag{Key: "tstype", Name: "string | null"}); err != nil {
				rewriteErr = err
				return false
			}
		}
		return true
	})
	return rewriteErr
}

func supportsJSONStringExpr(expr ast.Expr, named map[string]namedJSONType, path map[string]bool, allowPointer bool, depth int) (supported, nullable bool) {
	if depth > maxGenerationDepth {
		return false, false
	}
	if pointer, ok := expr.(*ast.StarExpr); ok {
		if !allowPointer {
			return false, false
		}
		supported, _ := supportsJSONStringExpr(pointer.X, named, path, false, depth+1)
		return supported, true
	}
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return false, false
	}
	switch ident.Name {
	case "bool", "string", "byte", "rune", "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64":
		return true, false
	}
	if path[ident.Name] {
		return false, false
	}
	underlying, ok := named[ident.Name]
	if !ok {
		return false, false
	}
	next := make(map[string]bool, len(path)+1)
	for name := range path {
		next[name] = true
	}
	next[ident.Name] = true
	// An alias preserves the identity of its target, so an alias to *int is the
	// same unnamed pointer reflection sees. A defined type introduces a new
	// identity; if its underlying type is a pointer, encoding/json does not apply
	// the string option through it.
	return supportsJSONStringExpr(underlying.expr, named, next, allowPointer && underlying.alias, depth+1)
}

func setStructTag(field *ast.Field, tag *structtag.Tag) error {
	body := ""
	if field.Tag != nil {
		unquoted, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			return fmt.Errorf("invalid struct tag: %w", err)
		}
		body = unquoted
	}
	tags, err := structtag.Parse(body)
	if err != nil {
		return fmt.Errorf("invalid struct tag: %w", err)
	}
	if err := tags.Set(tag); err != nil {
		return fmt.Errorf("set %s struct tag: %w", tag.Key, err)
	}
	field.Tag = &ast.BasicLit{Kind: token.STRING, Value: "`" + tags.String() + "`"}
	return nil
}

func renderExpr(expr ast.Expr) string {
	var out bytes.Buffer
	if err := printer.Fprint(&out, token.NewFileSet(), expr); err != nil {
		return "<unknown>"
	}
	return out.String()
}

// normalizeJSONTagValue mirrors encoding/json's handling of explicitly named
// fields while adapting its literal-dash edge case for tygo. An invalid name is
// ignored but its options remain active; "-," names the property "-", whereas
// the exact tag "-" omits the field.
func normalizeJSONTagValue(tag string) (string, bool) {
	if tag == "" || tag == "-" {
		return tag, false
	}
	name, options, hasOptions := strings.Cut(tag, ",")
	switch {
	case name == "-" && hasOptions:
		return literalDashTagSentinel + "," + options, true
	case name != "" && !validJSONTag(name):
		if hasOptions {
			return "," + options, true
		}
		return "", true
	default:
		return tag, false
	}
}

func setJSONTag(f *ast.Field, value string) {
	body := ""
	if f.Tag != nil {
		unquoted, err := strconv.Unquote(f.Tag.Value)
		if err != nil {
			return
		}
		body = unquoted
	}
	replacement := "json:" + strconv.Quote(value)
	if match := jsonStructTagRE.FindStringIndex(body); match != nil {
		prefix := body[match[0]:match[1]]
		leading := prefix[:len(prefix)-len(strings.TrimLeft(prefix, " \t"))]
		body = body[:match[0]] + leading + replacement + body[match[1]:]
	} else if body == "" {
		body = replacement
	} else {
		body += " " + replacement
	}
	f.Tag = &ast.BasicLit{Kind: token.STRING, Value: "`" + body + "`"}
}

// embeddedStructName returns the type name of an embedded (anonymous) field —
// unwrapping a leading pointer — and true when f is such a field. A field with
// explicit names, or an anonymous field of a non-ident type, returns false.
func embeddedStructName(f *ast.Field) (string, bool) {
	if len(f.Names) != 0 {
		return "", false
	}
	if tag, ok := fieldJSONTag(f); ok {
		if name, _, _ := strings.Cut(tag, ","); name == literalDashTagSentinel || name != "" && validJSONTag(name) {
			return "", false
		}
	}
	expr := f.Type
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}
	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name, true
	}
	return "", false
}

// hasPackageClause reports whether src already opens with a `package` clause,
// ignoring leading comments and blank lines.
func hasPackageClause(src string) bool {
	for _, line := range strings.Split(src, "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "//") || strings.HasPrefix(t, "/*") {
			continue
		}
		return strings.HasPrefix(t, "package ")
	}
	return false
}

// assembleTS prepends the Code-generated header to a tygo-rendered body and
// guarantees exactly one trailing newline, for a stable on-disk form.
func assembleTS(body string) []byte {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	buf.WriteString("\n")
	buf.WriteString(strings.TrimRight(body, "\n"))
	buf.WriteString("\n")
	return buf.Bytes()
}
