package codegen_test

import (
	"bytes"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/hurtener/dockyard/internal/codegen"
	"github.com/hurtener/dockyard/internal/codegen/testdata/externalcontract"
)

// generatedTSMarker is the canonical first line of every generated TypeScript
// file; AGENTS.md §5 mandates the "Code generated ... DO NOT EDIT." marker.
const generatedTSMarker = "// Code generated by dockyard; DO NOT EDIT."

// --- contract source fixtures ----------------------------------------------

const tsScalars = "// Profile is a contract.\n" +
	"type Profile struct {\n" +
	"\tName    string  `json:\"name\"`\n" +
	"\tAge     int     `json:\"age\"`\n" +
	"\tBalance float64 `json:\"balance\"`\n" +
	"\tActive  bool    `json:\"active\"`\n" +
	"\tNick    string  `json:\"nick,omitempty\"`\n" +
	"}\n"

const tsNested = "type Line struct {\n" +
	"\tSKU   string  `json:\"sku\"`\n" +
	"\tPrice float64 `json:\"price\"`\n" +
	"}\n\n" +
	"type Order struct {\n" +
	"\tID    string `json:\"id\"`\n" +
	"\tLines []Line `json:\"lines\"`\n" +
	"}\n"

// --- TypeScriptForSource ---------------------------------------------------

func TestTypeScriptForSource_Header(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	if !strings.HasPrefix(string(got), generatedTSMarker) {
		t.Errorf("output does not start with the generated marker:\n%s", got)
	}
	if !strings.HasSuffix(string(got), "\n") || strings.HasSuffix(string(got), "\n\n") {
		t.Errorf("output must end with exactly one trailing newline")
	}
}

func TestTypeScriptForSource_Scalars(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	for _, want := range []string{
		"export interface Profile {",
		"name: string;",
		"age: number",
		"balance: number",
		"active: boolean;",
		"nick?: string;", // omitempty ⇒ optional
	} {
		if !strings.Contains(s, want) {
			t.Errorf("generated TS missing %q\n%s", want, s)
		}
	}
}

func TestTypeScriptForSource_NestedAndSlice(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "export interface Line {") || !strings.Contains(s, "export interface Order {") {
		t.Errorf("both interfaces should be generated:\n%s", s)
	}
	if !strings.Contains(s, "lines: Line[];") {
		t.Errorf("slice field should render as Line[]:\n%s", s)
	}
}

func TestTypeScriptForSource_BytesUseBase64StringShape(t *testing.T) {
	t.Parallel()
	src := "type Payload struct {\n\tData []byte `json:\"data\"`\n\tChunks [][]uint8 `json:\"chunks\"`\n}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatal(err)
	}
	if text := string(got); !strings.Contains(text, "data: string;") || !strings.Contains(text, "chunks: string[];") {
		t.Fatalf("byte slices must match encoding/json base64 strings:\n%s", text)
	}
}

func TestTypeScriptForSource_ByteAliasesAndNestedFormsUseStrings(t *testing.T) {
	t.Parallel()
	src := "type Octet uint8\ntype MoreOctet Octet\ntype Payload struct {\n\tData []MoreOctet `json:\"data\"`\n\tNested map[string][][]Octet `json:\"nested\"`\n}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	if !strings.Contains(text, "data: string;") || !strings.Contains(text, "nested: { [key: string]: string[]};") {
		t.Fatalf("byte aliases must follow encoding/json through nested forms:\n%s", text)
	}
}

func TestTypeScriptForSource_TaggedAnonymousFieldIsNotFlattened(t *testing.T) {
	t.Parallel()
	src := "type Node struct {\n\t*Node `json:\"next,omitempty\"`\n}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatal(err)
	}
	if text := string(got); !strings.Contains(text, "next?: Node;") {
		t.Fatalf("tagged anonymous field must remain a named JSON property:\n%s", text)
	}
}

func TestTypeScriptForSource_InvalidAnonymousJSONTagIsPromoted(t *testing.T) {
	t.Parallel()
	src := "type Inner struct { Value string `json:\"value\"` }\ntype Outer struct { Inner `json:\"bad©name\"` }\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	outer := text[strings.Index(text, "export interface Outer"):]
	if !strings.Contains(outer, "value: string;") || strings.Contains(outer, "bad©name") || strings.Contains(outer, "Inner: Inner") {
		t.Fatalf("invalid JSON tag must be ignored like encoding/json:\n%s", text)
	}
}

func TestTypeScriptForSource_NormalizesNamedJSONTagsLikeEncodingJSON(t *testing.T) {
	t.Parallel()
	src := "type Marker string\n" +
		"const MarkerSentinel Marker = \"dockyard©json©literal©dash\"\n" +
		"type Payload struct {\n" +
		"\t// Dash preserves the text 'dockyard©json©literal©dash'.\n" +
		"\tDash string `json:\"-,\"`\n" +
		"\tFallback string `json:\"bad©name,omitempty\"`\n" +
		"\tReserved string `json:\"dockyard©json©literal©dash\"`\n}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	if !strings.Contains(text, "'-': string;") {
		t.Fatalf(`json:"-," must produce the literal JSON property "-":\n%s`, text)
	}
	if !strings.Contains(text, "Fallback?: string;") || strings.Contains(text, "bad©name") {
		t.Fatalf("invalid JSON tag names must fall back to the Go field name and retain options:\n%s", text)
	}
	if !strings.Contains(text, "Reserved: string;") {
		t.Fatalf("source text matching the internal dash sentinel must still use encoding/json fallback:\n%s", text)
	}
	if !strings.Contains(text, "'dockyard©json©literal©dash'.") ||
		!strings.Contains(text, `MarkerSentinel: Marker = "dockyard©json©literal©dash"`) {
		t.Fatalf("literal-dash normalization changed comment or string content:\n%s", text)
	}
}

func TestTypeScriptForSource_Deterministic(t *testing.T) {
	t.Parallel()
	a, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("first generation: %v", err)
	}
	b, err := codegen.TypeScriptForSource(tsNested)
	if err != nil {
		t.Fatalf("second generation: %v", err)
	}
	if string(a) != string(b) {
		t.Errorf("TypeScriptForSource is not deterministic:\n--- a ---\n%s\n--- b ---\n%s", a, b)
	}
}

func TestTypeScriptForSource_AcceptsPackageClause(t *testing.T) {
	t.Parallel()
	// A full file with a package clause and imports must work — TypeScriptForDir
	// reads real source files.
	src := "// Package contracts is the source of truth.\n" +
		"package contracts\n\n" +
		"import \"time\"\n\n" +
		"var _ = time.Now\n\n" +
		tsScalars
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatalf("TypeScriptForSource with package clause: %v", err)
	}
	if !strings.Contains(string(got), "export interface Profile {") {
		t.Errorf("type declaration not generated from a full-file source:\n%s", got)
	}
	if strings.Contains(string(got), "time") {
		t.Errorf("import-derived noise leaked into the output:\n%s", got)
	}
}

func TestTypeScriptForSource_RejectsUnresolvedImportedContractType(t *testing.T) {
	t.Parallel()
	src := "package contracts\nimport \"math/big\"\ntype Payload struct { Number big.Int `json:\"number\"` }\n"
	_, err := codegen.TypeScriptForSource(src)
	if !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "cannot safely resolve imported type big.Int") {
		t.Fatalf("big.Int source error = %v, want safe-resolution rejection", err)
	}
}

func TestTypeScriptForSource_RejectsUnresolvedImportedConstValue(t *testing.T) {
	t.Parallel()
	src := "package contracts\nimport \"time\"\nconst Timeout = time.Second\ntype Payload struct { Value string `json:\"value\"` }\n"
	_, err := codegen.TypeScriptForSource(src)
	if !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "cannot safely resolve imported value time.Second") {
		t.Fatalf("imported const value error = %v, want safe-resolution rejection", err)
	}
}

func TestTypeScriptForSource_RejectsDotImportedContractTypes(t *testing.T) {
	t.Parallel()
	src := "package contracts\nimport . \"math/big\"\ntype Payload struct { Number Int `json:\"number\"` }\n"
	_, err := codegen.TypeScriptForSource(src)
	if !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "cannot safely resolve dot-imported contract types") {
		t.Fatalf("dot-import source error = %v, want safe-resolution rejection", err)
	}
}

func TestTypeScriptForSource_WithIndent(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars, codegen.WithIndent("    "))
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	if !strings.Contains(string(got), "\n    name: string;") {
		t.Errorf("WithIndent(4 spaces) not honoured:\n%s", got)
	}
}

func TestTypeScriptForSource_WithNullOptional(t *testing.T) {
	t.Parallel()
	got, err := codegen.TypeScriptForSource(tsScalars, codegen.WithNullOptional())
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "nick: string | null;") {
		t.Errorf("WithNullOptional should render optional fields as `T | null`:\n%s", s)
	}
	if strings.Contains(s, "nick?:") {
		t.Errorf("WithNullOptional should not emit the `?` optional marker:\n%s", s)
	}
}

func TestTypeScriptForSource_InvalidSource(t *testing.T) {
	t.Parallel()
	_, err := codegen.TypeScriptForSource("type Broken struct { this is not go")
	if err == nil {
		t.Fatal("expected an error for unparseable Go source")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

// TestTypeScriptForSource_MalformedStructTagNoPanic is a Phase 21.5 regression
// test: the FuzzTypeScriptForSource target found that a struct field carrying a
// syntactically invalid struct tag drove the tygo dependency to panic ("bad
// syntax for struct tag pair") rather than return an error. TypeScriptForSource
// must now contain that panic and return an ErrTypeScriptGen error — a
// malformed contract file fails the codegen step cleanly, never crashes the
// process (CLAUDE.md §13).
func TestTypeScriptForSource_MalformedStructTagNoPanic(t *testing.T) {
	t.Parallel()
	// The tag `0` (a bare backtick-quoted value, not a key:"value" pair) is the
	// minimised crasher the fuzzer surfaced.
	const crasher = "type A0 struct {A0`0`} "
	_, err := codegen.TypeScriptForSource(crasher)
	if err == nil {
		t.Fatal("expected an error for a malformed struct tag, got nil")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

// TestGeneratedTSIsStructurallyValid checks the golden TypeScript fixtures are
// structurally valid TS: balanced braces, every declaration is a recognised
// export, and no `any /* ... */` fallback markers (tygo emits those for an
// unmapped Go type — a contract that produced one would not be cleanly typed).
// This is a hermetic stand-in for a full `tsc` compile; the codegen path stays
// Node-free (RFC §6.2, Design A).
func TestGeneratedTSIsStructurallyValid(t *testing.T) {
	t.Parallel()
	entries, err := os.ReadDir("testdata")
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}
	var checked int
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".ts.golden") {
			continue
		}
		checked++
		t.Run(e.Name(), func(t *testing.T) {
			t.Parallel()
			raw, err := os.ReadFile(filepath.Join("testdata", e.Name())) //nolint:gosec // fixed testdata path
			if err != nil {
				t.Fatalf("read fixture: %v", err)
			}
			ts := string(raw)
			assertBalanced(t, ts)
			if strings.Contains(ts, "any /*") {
				t.Errorf("fixture %s contains an unmapped-type fallback marker `any /* ... */`", e.Name())
			}
			if !strings.HasPrefix(ts, generatedTSMarker) {
				t.Errorf("fixture %s missing the generated marker", e.Name())
			}
		})
	}
	if checked == 0 {
		t.Fatal("no .ts.golden fixtures found — run -update")
	}
}

func assertBalanced(t *testing.T, ts string) {
	t.Helper()
	depth := 0
	for _, r := range ts {
		switch r {
		case '{':
			depth++
		case '}':
			depth--
			if depth < 0 {
				t.Fatalf("unbalanced braces: a `}` with no opener")
			}
		}
	}
	if depth != 0 {
		t.Fatalf("unbalanced braces: %d unclosed `{`", depth)
	}
}

// --- embedded-struct flattening (finding 4 / D-051) ------------------------

func TestTypeScriptForSource_EmbeddedStructFlattened(t *testing.T) {
	t.Parallel()
	src := "// Base carries shared fields.\n" +
		"type Base struct {\n" +
		"\tID   string `json:\"id\"`\n" +
		"\tKind string `json:\"kind\"`\n" +
		"}\n\n" +
		"// Widget embeds Base.\n" +
		"type Widget struct {\n" +
		"\tBase\n" +
		"\tTitle string `json:\"title\"`\n" +
		"}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	// The embedded struct's fields are inlined into Widget.
	for _, want := range []string{"id: string;", "kind: string;", "title: string;"} {
		if !strings.Contains(s, want) {
			t.Errorf("embedded field %q should be inlined into Widget:\n%s", want, s)
		}
	}
	// tygo's default `Base: Base;` named-property form must NOT appear.
	if strings.Contains(s, "Base: Base") {
		t.Errorf("embedded struct must be flattened, not emitted as a named property:\n%s", s)
	}
}

func TestTypeScriptForSource_EmbeddedTransitiveAndShadowing(t *testing.T) {
	t.Parallel()
	// AuditSpan embeds AuditEvent (which embeds AuditBase) and re-declares `kind`
	// — Go's "outer wins" promotion rule. The flattened interface must carry
	// `kind` exactly once.
	src := "type Inner struct {\n" +
		"\tID   string `json:\"id\"`\n" +
		"\tKind string `json:\"kind\"`\n" +
		"}\n\n" +
		"type Mid struct {\n" +
		"\tInner\n" +
		"\tTitle string `json:\"title\"`\n" +
		"}\n\n" +
		"type Outer struct {\n" +
		"\tMid\n" +
		"\tKind     string `json:\"kind\"`\n" +
		"\tDuration int    `json:\"duration\"`\n" +
		"}\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatalf("TypeScriptForSource: %v", err)
	}
	s := string(got)
	outer := s[strings.Index(s, "export interface Outer"):]
	outer = outer[:strings.Index(outer, "}")]
	if n := strings.Count(outer, "kind"); n != 1 {
		t.Errorf("`kind` should appear exactly once in Outer (outer wins), got %d:\n%s", n, outer)
	}
	for _, want := range []string{"id", "title", "duration"} {
		if !strings.Contains(outer, want) {
			t.Errorf("transitively promoted field %q missing from Outer:\n%s", want, outer)
		}
	}
}

func TestTypeScriptForSource_EmbeddedDominanceAndPointerOptionality(t *testing.T) {
	t.Parallel()
	src := "type Left struct { Value string }\n" +
		"type Right struct { Value string }\n" +
		"type Ambiguous struct { Left; Right }\n" +
		"type Tagged struct { Plain; Named }\n" +
		"type Plain struct { Value string }\n" +
		"type Named struct { Value string `json:\"Value\"` }\n" +
		"type Optional struct { *Left }\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	ambiguous := interfaceBody(t, text, "Ambiguous")
	if strings.Contains(ambiguous, "Value") {
		t.Fatalf("equally dominant fields must remain ambiguous and be omitted:\n%s", ambiguous)
	}
	tagged := interfaceBody(t, text, "Tagged")
	if strings.Count(tagged, "Value") != 1 {
		t.Fatalf("a tagged field must dominate an untagged field at the same depth:\n%s", tagged)
	}
	optional := interfaceBody(t, text, "Optional")
	if !strings.Contains(optional, "Value?: string;") {
		t.Fatalf("a field promoted through a pointer ancestor must be optional:\n%s", optional)
	}
}

func TestTypeScriptForSource_PromotedFieldPreservesComment(t *testing.T) {
	t.Parallel()
	src := "type Base struct {\n// ID identifies the object.\nID string `json:\"id\"`\n}\ntype Payload struct { Base }\n"
	got, err := codegen.TypeScriptForSource(src)
	if err != nil {
		t.Fatal(err)
	}
	body := string(got)[strings.Index(string(got), "export interface Payload"):]
	if !strings.Contains(body, "ID identifies the object") || !strings.Contains(body, "id: string;") {
		t.Fatalf("promoted field lost its JSDoc:\n%s", got)
	}
}

func TestTypeScriptForSource_RejectsEmbeddedForeignType(t *testing.T) {
	t.Parallel()
	// Source-only generation cannot inspect an imported type's wire behavior, so
	// it must reject rather than let tygo degrade the field to any.
	src := "type Widget struct {\n" +
		"\tsync.Mutex\n" +
		"\tName string `json:\"name\"`\n" +
		"}\n"
	_, err := codegen.TypeScriptForSource(src)
	if !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "cannot safely resolve imported type sync.Mutex") {
		t.Fatalf("foreign embedded type error = %v, want safe-resolution rejection", err)
	}
}

// --- TypeScriptForDir ------------------------------------------------------

func TestTypeScriptForDir(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	// Two contract files plus a test file that must be ignored. Files are read
	// in sorted name order: a_types.go before b_types.go.
	writeFile(t, dir, "b_types.go", "package contracts\n\n"+
		"type Beta struct {\n\tID string `json:\"id\"`\n}\n")
	writeFile(t, dir, "a_types.go", "package contracts\n\n"+
		"type Alpha struct {\n\tName string `json:\"name\"`\n}\n")
	writeFile(t, dir, "x_types_test.go", "package contracts\n\n"+
		"type ShouldBeIgnored struct {\n\tX int `json:\"x\"`\n}\n")

	got, err := codegen.TypeScriptForDir(dir)
	if err != nil {
		t.Fatalf("TypeScriptForDir: %v", err)
	}
	s := string(got)
	if !strings.Contains(s, "export interface Alpha {") || !strings.Contains(s, "export interface Beta {") {
		t.Errorf("both contract files should be generated:\n%s", s)
	}
	if strings.Contains(s, "ShouldBeIgnored") {
		t.Errorf("_test.go file should be ignored:\n%s", s)
	}
	// Sorted order: Alpha (a_types.go) precedes Beta (b_types.go).
	if strings.Index(s, "Alpha") > strings.Index(s, "Beta") {
		t.Errorf("declarations should appear in sorted-filename order:\n%s", s)
	}
}

func TestTypeScriptForDir_SkipsGeneratedGoFiles(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	writeFile(t, dir, "contracts.go", "package contracts\ntype Real struct { Value string }\n")
	writeFile(t, dir, "suffix.generated.go", "package contracts\ntype SuffixGenerated struct { Value string }\n")
	writeFile(t, dir, "marker_gen.go", "// Code generated by another tool. DO NOT EDIT.\npackage contracts\ntype MarkerGenerated struct { Value string }\n")
	got, err := codegen.TypeScriptForDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	if !strings.Contains(text, "export interface Real") || strings.Contains(text, "SuffixGenerated") || strings.Contains(text, "MarkerGenerated") {
		t.Fatalf("generated Go declarations leaked into contracts.ts:\n%s", got)
	}
}

func TestTypeScriptForDir_ImportedLocalByteAliasUsesString(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, root, "go.mod", "module example.com/bytes\n\ngo 1.26.2\n")
	for _, dir := range []string{"shared", "contracts"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, root, "shared/types.go", "package shared\ntype Octet uint8\ntype More Octet\n")
	contractsDir := filepath.Join(root, "contracts")
	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"example.com/bytes/shared\"\ntype Payload struct { Data []shared.More `json:\"data\"` }\n")
	got, err := codegen.TypeScriptForDir(contractsDir)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "data: string;") {
		t.Fatalf("imported local byte alias must use its wire shape:\n%s", got)
	}
}

func TestTypeScriptForDir_ImportedExternalModuleByteAliasUsesStringOffline(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for _, dir := range []string{"wire", "contracts"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, root, "go.mod", "module example.com/app\n\ngo 1.26.2\n\nrequire example.com/wire v0.0.0\nreplace example.com/wire => ./wire\n")
	writeFile(t, root, "wire/go.mod", "module example.com/wire\n\ngo 1.26.2\n")
	writeFile(t, root, "wire/types.go", "package octets\ntype Octet uint8\ntype More Octet\ntype Word uint16\ntype Words []Word\ntype Lookup map[string]Word\ntype Pair [2]Word\ntype Meta struct { Label string `json:\"label\"`; Raw []byte `json:\"raw\"`; hidden string }\n")
	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport wire \"example.com/wire\"\ntype Payload struct { Data []wire.More `json:\"data\"`; Words wire.Words `json:\"words\"`; Lookup wire.Lookup `json:\"lookup\"`; Pair wire.Pair `json:\"pair\"`; Meta wire.Meta `json:\"meta\"` }\n")

	got, err := codegen.TypeScriptForDir(filepath.Join(root, "contracts"))
	if err != nil {
		t.Fatal(err)
	}
	body := interfaceBody(t, string(got), "Payload")
	if !strings.Contains(body, "data: string;") {
		t.Fatalf("external-module byte alias must use its base64 wire shape:\n%s", got)
	}
	text := string(got)
	for _, want := range []string{
		"words: number /* uint16 */[];",
		"lookup: { [key: string]: number /* uint16 */};",
		"pair: number /* uint16 */[];",
		"meta: {",
		"label: string;",
		"raw: string;",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("imported wire shape missing %q:\n%s", want, got)
		}
	}
	if strings.Contains(text, "wire.") || strings.Contains(text, "hidden") {
		t.Fatalf("generated TypeScript retained an undefined package selector or hidden field:\n%s", got)
	}

	tsc := filepath.Join("..", "..", "web", "inspector", "node_modules", ".bin", "tsc")
	if _, err := os.Stat(tsc); err != nil {
		t.Log("TypeScript compiler is not installed; syntax regression covered by shape assertions")
		return
	}
	tsPath := filepath.Join(root, "contracts.ts")
	if err := os.WriteFile(tsPath, got, 0o600); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(tsc, "--noEmit", "--strict", "--skipLibCheck", "--target", "ES2022", tsPath) //nolint:gosec // tsc is a repository-local test dependency.
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated TypeScript does not typecheck: %v\n%s\n%s", err, output, got)
	}
}

func TestTypeScriptForDir_FlattensImportedAnonymousStruct(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for _, dir := range []string{"wire", "contracts"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, root, "go.mod", "module example.com/importedembed\n\ngo 1.26.2\n")
	writeFile(t, root, "wire/types.go", "package wire\ntype Base struct { ID string `json:\"id\"` }\n")
	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"example.com/importedembed/wire\"\ntype Payload struct { *wire.Base; Name string `json:\"name\"` }\n")
	got, err := codegen.TypeScriptForDir(filepath.Join(root, "contracts"))
	if err != nil {
		t.Fatal(err)
	}
	body := interfaceBody(t, string(got), "Payload")
	if !strings.Contains(body, "id?: string;") || !strings.Contains(body, "name: string;") || strings.Contains(body, "Base:") {
		t.Fatalf("imported anonymous struct was not promoted with pointer optionality:\n%s", got)
	}
}

func TestTypeScriptForDir_ImportedNamedByteSliceUsesStringAndCrossChecks(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for _, dir := range []string{"wire", "contracts"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, root, "go.mod", "module example.com/app\n\ngo 1.26.2\n\nrequire example.com/wire v0.0.0\nreplace example.com/wire => ./wire\n")
	writeFile(t, root, "wire/go.mod", "module example.com/wire\n\ngo 1.26.2\n")
	writeFile(t, root, "wire/types.go", "package wire\ntype Bytes []byte\ntype MoreBytes Bytes\ntype Words []uint16\n")
	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"example.com/wire\"\ntype Payload struct { Data wire.MoreBytes `json:\"data\"`; Words wire.Words `json:\"words\"` }\n")

	got, err := codegen.TypeScriptForDir(filepath.Join(root, "contracts"))
	if err != nil {
		t.Fatal(err)
	}
	body := interfaceBody(t, string(got), "Payload")
	if !strings.Contains(body, "data: string;") {
		t.Fatalf("imported named byte slice must use its base64 wire shape:\n%s", got)
	}
	if strings.Contains(body, "words: string;") {
		t.Fatalf("non-byte imported slice was rewritten as base64:\n%s", got)
	}
	schema := &jsonschema.Schema{
		Type:     "object",
		Required: []string{"data", "words"},
		Properties: map[string]*jsonschema.Schema{
			"data":  {Type: "string", ContentEncoding: "base64"},
			"words": {Type: "array"},
		},
	}
	if err := codegen.CrossCheck(schema, "Payload", got); err != nil {
		t.Fatalf("generated named-byte-slice TypeScript must match schema: %v", err)
	}
	bad := []byte(strings.Replace(string(got), "data: string;", "data: wire.MoreBytes;", 1))
	if err := codegen.CrossCheck(schema, "Payload", bad); !errors.Is(err, codegen.ErrSchemaTSDrift) {
		t.Fatalf("CrossCheck error = %v, want ErrSchemaTSDrift", err)
	}
}

func TestTypeScriptForDir_ImportedStructJSONNamesMatchSchemaAndCompile(t *testing.T) {
	t.Parallel()

	schema, err := codegen.SchemaFor[externalcontract.Payload]()
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := schema.Properties["-"]; !ok {
		t.Fatal(`schema must retain json:"-," as the literal property "-"`)
	}
	if fallback := schema.Properties["Fallback"]; fallback == nil {
		t.Fatal("invalid JSON name must fall back to the Go field name")
	}
	if _, ok := schema.Properties["Ignored"]; ok {
		t.Fatal(`schema must omit the exact tag json:"-"`)
	}

	got, err := codegen.TypeScriptForDir(filepath.Join("testdata", "externalcontract"))
	if err != nil {
		t.Fatal(err)
	}
	body := interfaceBody(t, string(got), "Payload")
	if !strings.Contains(body, "'-': string;") {
		t.Fatalf(`imported json:"-," field must use the literal property "-":\n%s`, got)
	}
	if !strings.Contains(body, "Fallback?: string;") || strings.Contains(body, "bad©name") {
		t.Fatalf("invalid imported JSON name must fall back while retaining options:\n%s", got)
	}
	if strings.Contains(body, "Ignored") {
		t.Fatalf(`imported field tagged json:"-" must be omitted:\n%s`, got)
	}
	if err := codegen.CrossCheck(schema, "Payload", got); err != nil {
		t.Fatalf("imported field schema/TypeScript drift: %v\n%s", err, got)
	}

	tsc := filepath.Join("..", "..", "web", "inspector", "node_modules", ".bin", "tsc")
	if _, err := os.Stat(tsc); err != nil {
		t.Log("TypeScript compiler is not installed; syntax covered by shape assertions")
		return
	}
	tsPath := filepath.Join(t.TempDir(), "contracts.ts")
	if err := os.WriteFile(tsPath, got, 0o600); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(tsc, "--noEmit", "--strict", "--skipLibCheck", "--target", "ES2022", tsPath) //nolint:gosec // tsc is a repository-local test dependency.
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated TypeScript does not typecheck: %v\n%s\n%s", err, output, got)
	}
}

func TestTypeScriptForSource_JSONStringOption(t *testing.T) {
	t.Parallel()
	source := "type ByteAlias = byte\ntype RuneAlias = rune\ntype BytePointerAlias = *byte\ntype RunePointerAlias = *rune\ntype ScalarBase int\ntype Scalar ScalarBase\ntype Payload struct { Byte byte `json:\"byte,string\"`; Rune rune `json:\"rune,string\"`; ByteAlias ByteAlias `json:\"byte_alias,string\"`; RuneAlias RuneAlias `json:\"rune_alias,string\"`; BytePointer BytePointerAlias `json:\"byte_pointer,string\"`; RunePointer RunePointerAlias `json:\"rune_pointer,string\"`; Count int `json:\"count,string\"`; Limit *Scalar `json:\"limit,string\"`; Maybe *Scalar `json:\"maybe,string,omitempty\"`; Flag *bool `json:\"flag,string\"`; Ratio *float64 `json:\"ratio,string\"`; Text *string `json:\"text,string\"` }"
	got, err := codegen.TypeScriptForSource(source)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	for _, want := range []string{"byte: string;", "rune: string;", "byte_alias: string;", "rune_alias: string;", "byte_pointer: string | null;", "rune_pointer: string | null;", "count: string;", "limit: string | null;", "maybe?: string | null;", "flag: string | null;", "ratio: string | null;", "text: string | null;"} {
		if !strings.Contains(text, want) {
			t.Fatalf("json ,string field missing %q:\n%s", want, got)
		}
	}
	nullOptional, err := codegen.TypeScriptForSource(source, codegen.WithNullOptional())
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(nullOptional), "maybe: string | null;") || strings.Contains(string(nullOptional), "null | null") {
		t.Fatalf("nullable optional pointer has the wrong null style:\n%s", nullOptional)
	}
	_, err = codegen.TypeScriptForSource("type Payload struct { Values []int `json:\"values,string\"` }")
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Fatalf("unsupported ,string error = %v, want ErrTypeScriptGen", err)
	}
	_, err = codegen.TypeScriptForSource("type Payload struct { Values *[]int `json:\"values,string\"` }")
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Fatalf("unsupported pointer target error = %v, want ErrTypeScriptGen", err)
	}
	for _, source := range []string{
		"type Payload struct { Value **int `json:\"value,string\"` }",
		"type Pointer *int\ntype Payload struct { Value Pointer `json:\"value,string\"` }",
	} {
		if _, err := codegen.TypeScriptForSource(source); !errors.Is(err, codegen.ErrTypeScriptGen) {
			t.Fatalf("unsupported pointer form error = %v, want ErrTypeScriptGen", err)
		}
	}
}

func TestTypeScriptForSource_JSONStringPointerAlias(t *testing.T) {
	t.Parallel()
	source := "type Pointer = *int\ntype Payload struct { Value Pointer `json:\"value,string\"` }"
	got, err := codegen.TypeScriptForSource(source)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "value: string | null;") {
		t.Fatalf("pointer alias must retain unnamed-pointer string behavior:\n%s", got)
	}

	for _, source := range []string{
		"type Pointer *int\ntype Payload struct { Value Pointer `json:\"value,string\"` }",
		"type Pointer *int\ntype Alias = Pointer\ntype Payload struct { Value Alias `json:\"value,string\"` }",
	} {
		if _, err := codegen.TypeScriptForSource(source); !errors.Is(err, codegen.ErrTypeScriptGen) {
			t.Fatalf("defined pointer form error = %v, want ErrTypeScriptGen", err)
		}
	}
}

func TestTypeScriptForDir_JSONStringDeclarationsAcrossFiles(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	contractsDir := filepath.Join(root, "contracts")
	if err := os.MkdirAll(contractsDir, 0o750); err != nil {
		t.Fatal(err)
	}
	writeFile(t, root, "go.mod", "module example.com/jsonstring\n\ngo 1.26.2\n")
	writeFile(t, root, "contracts/a_scalar.go", "package contracts\ntype Scalar int\ntype Count int\ntype ByteAlias = byte\ntype RuneAlias = rune\n")
	writeFile(t, root, "contracts/b_pointer.go", "package contracts\ntype Pointer = *Scalar\n")
	writeFile(t, root, "contracts/c_alias.go", "package contracts\ntype PointerAlias = Pointer\ntype BytePointerAlias = *ByteAlias\ntype RunePointerAlias = *RuneAlias\n")
	writeFile(t, root, "contracts/z_payload.go", "package contracts\ntype Payload struct { Value PointerAlias `json:\"value,string\"`; Byte ByteAlias `json:\"byte,string\"`; Rune RuneAlias `json:\"rune,string\"`; BytePointer BytePointerAlias `json:\"byte_pointer,string\"`; RunePointer RunePointerAlias `json:\"rune_pointer,string\"`; Count `json:\"count,string\"` }\n")

	first, err := codegen.TypeScriptForDir(contractsDir)
	if err != nil {
		t.Fatal(err)
	}
	body := interfaceBody(t, string(first), "Payload")
	for _, want := range []string{"value: string | null;", "byte: string;", "rune: string;", "byte_pointer: string | null;", "rune_pointer: string | null;", "count: string;"} {
		if !strings.Contains(body, want) {
			t.Fatalf("cross-file json ,string declaration missing %q:\n%s", want, first)
		}
	}
	for range 5 {
		again, err := codegen.TypeScriptForDir(contractsDir)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(first, again) {
			t.Fatalf("cross-file json ,string output is nondeterministic:\n%s\n---\n%s", first, again)
		}
	}
}

func TestTypeScriptForDir_JSONStringCrossFileRejections(t *testing.T) {
	t.Parallel()
	for name, declarations := range map[string]map[string]string{
		"defined pointer": {
			"a.go": "type Pointer *int",
			"b.go": "type Alias = Pointer",
			"z.go": "type Payload struct { Value Alias `json:\"value,string\"` }",
		},
		"alias cycle": {
			"a.go": "type First = Second",
			"b.go": "type Second = First",
			"z.go": "type Payload struct { Value First `json:\"value,string\"` }",
		},
	} {
		t.Run(name, func(t *testing.T) {
			root := t.TempDir()
			contractsDir := filepath.Join(root, "contracts")
			if err := os.MkdirAll(contractsDir, 0o750); err != nil {
				t.Fatal(err)
			}
			writeFile(t, root, "go.mod", "module example.com/rejected\n\ngo 1.26.2\n")
			for filename, declaration := range declarations {
				writeFile(t, root, "contracts/"+filename, "package contracts\n"+declaration+"\n")
			}
			_, firstErr := codegen.TypeScriptForDir(contractsDir)
			_, secondErr := codegen.TypeScriptForDir(contractsDir)
			if !errors.Is(firstErr, codegen.ErrTypeScriptGen) {
				t.Fatalf("first error = %v, want ErrTypeScriptGen", firstErr)
			}
			if firstErr.Error() != secondErr.Error() {
				t.Fatalf("rejection is nondeterministic:\n%v\n%v", firstErr, secondErr)
			}
		})
	}
}

func TestTypeScriptForSource_JSONStringTaggedAnonymousScalar(t *testing.T) {
	t.Parallel()
	source := "type CountBase int\ntype Count = CountBase\ntype Limit int\ntype Payload struct { Count `json:\"count,string\"`; *Limit `json:\"limit,string\"` }"
	got, err := codegen.TypeScriptForSource(source)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	for _, want := range []string{"count: string;", "limit: string | null;"} {
		if !strings.Contains(text, want) {
			t.Fatalf("tagged anonymous scalar missing %q:\n%s", want, got)
		}
	}
}

func TestTypeScriptForDir_ImportedStandardWireTypesAndCustomMarshaler(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	contractsDir := filepath.Join(root, "contracts")
	if err := os.MkdirAll(contractsDir, 0o750); err != nil {
		t.Fatal(err)
	}
	writeFile(t, root, "go.mod", "module example.com/special\n\ngo 1.26.2\n")
	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"log/slog\"\ntype Payload struct { Level slog.Level `json:\"level\"` }\n")
	got, err := codegen.TypeScriptForDir(contractsDir)
	if err != nil {
		t.Fatal(err)
	}
	body := interfaceBody(t, string(got), "Payload")
	for _, want := range []string{"level: string;"} {
		if !strings.Contains(body, want) {
			t.Fatalf("standard wire type missing %q:\n%s", want, got)
		}
	}
	schema := &jsonschema.Schema{Type: "object", Required: []string{"level"}, Properties: map[string]*jsonschema.Schema{
		"level": {Type: "string"},
	}}
	if err := codegen.CrossCheck(schema, "Payload", got); err != nil {
		t.Fatalf("standard wire type schema/TypeScript drift: %v", err)
	}
	for _, typeName := range []string{"Int", "Rat", "Float"} {
		for _, pointer := range []string{"", "*"} {
			form := "value"
			if pointer != "" {
				form = "pointer"
			}
			writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"math/big\"\ntype Payload struct { Number "+pointer+"big."+typeName+" `json:\"number\"` }\n")
			if _, err := codegen.TypeScriptForDir(contractsDir); !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "custom JSON encoding") {
				t.Fatalf("nested big.%s %s custom marshaler error = %v", typeName, form, err)
			}
			writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"math/big\"\ntype Payload = "+pointer+"big."+typeName+"\n")
			if _, err := codegen.TypeScriptForDir(contractsDir); !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "custom JSON encoding") {
				t.Fatalf("root big.%s %s custom marshaler error = %v", typeName, form, err)
			}
		}
	}

	if err := os.MkdirAll(filepath.Join(root, "wire"), 0o750); err != nil {
		t.Fatal(err)
	}
	writeFile(t, root, "wire/types.go", "package wire\ntype Custom struct { Value string }\nfunc (Custom) MarshalJSON() ([]byte, error) { return []byte(`\"custom\"`), nil }\n")
	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"example.com/special/wire\"\ntype Payload struct { Value wire.Custom `json:\"value\"` }\n")
	if _, err := codegen.TypeScriptForDir(contractsDir); !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "custom JSON encoding") {
		t.Fatalf("custom marshaler error = %v", err)
	}
}

func TestTypeScriptForDir_CustomEncodingInspectionSkipsOnlyExactJSONDash(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	contractsDir := filepath.Join(root, "contracts")
	for _, dir := range []string{contractsDir, filepath.Join(root, "wire")} {
		if err := os.MkdirAll(dir, 0o750); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, root, "go.mod", "module example.com/ignoredcustom\n\ngo 1.26.2\n")
	writeFile(t, root, "wire/types.go", "package wire\ntype Custom struct { Value string }\nfunc (Custom) MarshalJSON() ([]byte, error) { return nil, nil }\n")
	writeFile(t, root, "contracts/contracts.go", `package contracts
import (
	"math/big"
	"example.com/ignoredcustom/wire"
)
type Payload struct {
	Int big.Int `+"`json:\"-\"`"+`
	Rat *big.Rat `+"`json:\"-\"`"+`
	Float big.Float `+"`json:\"-\"`"+`
	Custom wire.Custom `+"`json:\"-\"`"+`
}
`)
	got, err := codegen.TypeScriptForDir(contractsDir)
	if err != nil {
		t.Fatalf("ignored math/big fields rejected: %v", err)
	}
	body := interfaceBody(t, string(got), "Payload")
	if strings.Contains(body, "Int") || strings.Contains(body, "Rat") || strings.Contains(body, "Float") || strings.Contains(body, "Custom") {
		t.Fatalf("ignored fields leaked into TypeScript:\n%s", got)
	}

	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"math/big\"\ntype Payload struct { Literal big.Rat `json:\"-,\"` }\n")
	if _, err := codegen.TypeScriptForDir(contractsDir); !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "custom JSON encoding") {
		t.Fatalf(`literal json:"-," error = %v, want custom encoding rejection`, err)
	}
}

func TestTypeScriptForDir_LocalCustomJSONEncoding(t *testing.T) {
	tests := map[string]string{
		"json value receiver":   "func (Custom) MarshalJSON() ([]byte, error) { return nil, nil }",
		"json pointer receiver": "func (*Custom) MarshalJSON() ([]byte, error) { return nil, nil }",
		"text value receiver":   "func (Custom) MarshalText() ([]byte, error) { return nil, nil }",
		"text pointer receiver": "func (*Custom) MarshalText() ([]byte, error) { return nil, nil }",
	}
	for name, method := range tests {
		t.Run(name, func(t *testing.T) {
			root := t.TempDir()
			if err := os.MkdirAll(filepath.Join(root, "contracts"), 0o750); err != nil {
				t.Fatal(err)
			}
			writeFile(t, root, "go.mod", "module example.com/localcustom\n\ngo 1.26.2\n")
			writeFile(t, root, "contracts/contracts.go", "package contracts\ntype Custom struct { Value string `json:\"value\"` }\n"+method+"\ntype Payload struct { Custom Custom `json:\"custom\"` }\n")
			_, err := codegen.TypeScriptForDir(filepath.Join(root, "contracts"))
			if !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "custom JSON encoding") {
				t.Fatalf("TypeScriptForDir error = %v, want custom encoding rejection", err)
			}
		})
	}
}

func TestTypeScriptForDir_MarshalerMethodNamesRequireExactSignature(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "contracts"), 0o750); err != nil {
		t.Fatal(err)
	}
	writeFile(t, root, "go.mod", "module example.com/samename\n\ngo 1.26.2\n")
	writeFile(t, root, "contracts/contracts.go", `package contracts
type JSONNameOnly struct { Value string `+"`json:\"value\"`"+` }
func (JSONNameOnly) MarshalJSON() string { return "ordinary method" }
type TextNameOnly struct { Value string `+"`json:\"value\"`"+` }
func (*TextNameOnly) MarshalText(string) ([]byte, error) { return nil, nil }
type Payload struct { JSON JSONNameOnly `+"`json:\"json\"`"+`; Text TextNameOnly `+"`json:\"text\"`"+` }
`)
	got, err := codegen.TypeScriptForDir(filepath.Join(root, "contracts"))
	if err != nil {
		t.Fatal(err)
	}
	body := interfaceBody(t, string(got), "Payload")
	if !strings.Contains(body, "json: JSONNameOnly;") || !strings.Contains(body, "text: TextNameOnly;") {
		t.Fatalf("same-name ordinary methods changed generated types:\n%s", got)
	}
}

func TestTypeScriptForDir_ImportedCustomEncodingReceiverMatrix(t *testing.T) {
	tests := map[string]string{
		"json value receiver":   "func (Custom) MarshalJSON() ([]byte, error) { return nil, nil }",
		"json pointer receiver": "func (*Custom) MarshalJSON() ([]byte, error) { return nil, nil }",
		"text value receiver":   "func (Custom) MarshalText() ([]byte, error) { return nil, nil }",
		"text pointer receiver": "func (*Custom) MarshalText() ([]byte, error) { return nil, nil }",
	}
	for name, method := range tests {
		t.Run(name, func(t *testing.T) {
			root := t.TempDir()
			for _, dir := range []string{"wire", "contracts"} {
				if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
					t.Fatal(err)
				}
			}
			writeFile(t, root, "go.mod", "module example.com/importcustom\n\ngo 1.26.2\n")
			writeFile(t, root, "wire/types.go", "package wire\ntype Custom struct { Value string }\n"+method+"\n")
			writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"example.com/importcustom/wire\"\ntype Payload struct { Value wire.Custom `json:\"value\"` }\n")
			_, err := codegen.TypeScriptForDir(filepath.Join(root, "contracts"))
			if !errors.Is(err, codegen.ErrTypeScriptGen) || !strings.Contains(err.Error(), "custom JSON encoding") {
				t.Fatalf("TypeScriptForDir error = %v, want custom encoding rejection", err)
			}
		})
	}

	root := t.TempDir()
	for _, dir := range []string{"wire", "contracts"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, root, "go.mod", "module example.com/importordinary\n\ngo 1.26.2\n")
	writeFile(t, root, "wire/types.go", "package wire\ntype Custom struct { Value string `json:\"value\"` }\nfunc (Custom) MarshalJSON() string { return \"ordinary\" }\nfunc (*Custom) MarshalText(string) ([]byte, error) { return nil, nil }\n")
	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"example.com/importordinary/wire\"\ntype Payload struct { Value wire.Custom `json:\"value\"` }\n")
	got, err := codegen.TypeScriptForDir(filepath.Join(root, "contracts"))
	if err != nil {
		t.Fatalf("same-name imported methods rejected: %v", err)
	}
	if !strings.Contains(interfaceBody(t, string(got), "Payload"), "value: {") {
		t.Fatalf("imported ordinary struct was not expanded:\n%s", got)
	}
}

func TestTypeScriptForDir_PreservesImportedRecursiveType(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	for _, dir := range []string{"wire", "contracts"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, root, "go.mod", "module example.com/recursive\n\ngo 1.26.2\n")
	writeFile(t, root, "wire/types.go", "package wire\ntype Node struct { Value string `json:\"value\"`; Next *Node `json:\"next,omitempty\"` }\n")
	writeFile(t, root, "contracts/contracts.go", "package contracts\nimport \"example.com/recursive/wire\"\ntype Payload struct { Root wire.Node `json:\"root\"` }\n")
	got, err := codegen.TypeScriptForDir(filepath.Join(root, "contracts"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	if strings.Contains(text, "next?: any") || !strings.Contains(text, "export interface DockyardImportedNode_") {
		t.Fatalf("recursive imported type was not preserved as a declaration:\n%s", got)
	}
	schema := &jsonschema.Schema{Type: "object", Required: []string{"root"}, Properties: map[string]*jsonschema.Schema{"root": {Type: "object"}}}
	if err := codegen.CrossCheck(schema, "Payload", got); err != nil {
		t.Fatalf("recursive declaration cross-check: %v\n%s", err, got)
	}
	bad := []byte(regexp.MustCompile(`DockyardImportedNode_[0-9a-f]+`).ReplaceAllString(text, "any"))
	if err := codegen.CrossCheck(schema, "Payload", bad); !errors.Is(err, codegen.ErrSchemaTSDrift) {
		t.Fatalf("CrossCheck accepted any for known object: %v", err)
	}
}

func TestTypeScriptForDir_ImportedByteAliasesAreFileScopedAndUseDeclaredPackageName(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, root, "go.mod", "module example.com/scopedbytes\n\ngo 1.26.2\n")
	for _, dir := range []string{"bytepath", "numberpath", "contracts"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o750); err != nil {
			t.Fatal(err)
		}
	}
	writeFile(t, root, "bytepath/types.go", "package wire\ntype Octet uint8\n")
	writeFile(t, root, "numberpath/types.go", "package numeric\ntype Octet uint16\n")
	contractsDir := filepath.Join(root, "contracts")
	writeFile(t, root, "contracts/a.go", "package contracts\nimport \"example.com/scopedbytes/bytepath\"\ntype Bytes struct { Data []wire.Octet `json:\"data\"` }\n")
	writeFile(t, root, "contracts/b.go", "package contracts\nimport wire \"example.com/scopedbytes/numberpath\"\ntype Numbers struct { Data []wire.Octet `json:\"numbers\"` }\n")
	got, err := codegen.TypeScriptForDir(contractsDir)
	if err != nil {
		t.Fatal(err)
	}
	text := string(got)
	if !strings.Contains(interfaceBody(t, text, "Bytes"), "data: string;") {
		t.Fatalf("default import must use its declared package name:\n%s", text)
	}
	numbers := interfaceBody(t, text, "Numbers")
	if strings.Contains(numbers, "numbers: string;") || !strings.Contains(numbers, "[];") {
		t.Fatalf("a byte alias from another file must not leak through a reused import alias:\n%s", text)
	}
}

func TestTypeScriptForDir_FlattensEmbeddedStructAcrossFiles(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, root, "go.mod", "module example.com/embedded\n\ngo 1.26.2\n")
	contractsDir := filepath.Join(root, "contracts")
	if err := os.MkdirAll(contractsDir, 0o750); err != nil {
		t.Fatal(err)
	}
	writeFile(t, root, "contracts/base.go", "package contracts\ntype Base struct { ID string `json:\"id\"` }\n")
	writeFile(t, root, "contracts/output.go", "package contracts\ntype Output struct { *Base }\n")
	got, err := codegen.TypeScriptForDir(contractsDir)
	if err != nil {
		t.Fatal(err)
	}
	body := interfaceBody(t, string(got), "Output")
	if !strings.Contains(body, "id?: string;") || strings.Contains(body, "Base: Base") {
		t.Fatalf("cross-file pointer embedding must flatten with optional promoted fields:\n%s", got)
	}
}

func interfaceBody(t *testing.T, source, name string) string {
	t.Helper()
	start := strings.Index(source, "export interface "+name)
	if start < 0 {
		t.Fatalf("interface %s not found:\n%s", name, source)
	}
	body := source[start:]
	end := strings.Index(body, "}")
	if end < 0 {
		t.Fatalf("interface %s is unterminated:\n%s", name, source)
	}
	return body[:end]
}

func TestTypeScriptForDir_Empty(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	_, err := codegen.TypeScriptForDir(dir)
	if err == nil {
		t.Fatal("expected an error for a directory with no contract files")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

func TestTypeScriptForDir_Missing(t *testing.T) {
	t.Parallel()
	_, err := codegen.TypeScriptForDir(filepath.Join(t.TempDir(), "does-not-exist"))
	if err == nil {
		t.Fatal("expected an error for a missing directory")
	}
	if !errors.Is(err, codegen.ErrTypeScriptGen) {
		t.Errorf("error should wrap ErrTypeScriptGen, got %v", err)
	}
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}
