package codegen

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/gzuidhof/tygo/tygo"
)

// generatedTSHeader is the banner placed at the top of every generated
// TypeScript file. The first line is the canonical `Code generated … DO NOT
// EDIT.` marker (AGENTS.md §5) — tools and reviewers recognise it, and it tells
// an app author the file is regenerated, never hand-edited (RFC §6.2).
const generatedTSHeader = `// Code generated by dockyard; DO NOT EDIT.
//
// TypeScript contract types — the UI-facing half of the Design A codegen
// pipeline (RFC §6.2). Generated from the Go contract structs by github.com/
// gzuidhof/tygo. The Go struct is the single source of truth (P1); regenerate
// with ` + "`dockyard generate`" + ` and never edit this file by hand.
`

// ErrTypeScriptGen is returned when Go contract source cannot be converted to
// TypeScript. It wraps the underlying tygo parse/convert failure so callers can
// branch with errors.Is.
var ErrTypeScriptGen = errors.New("dockyard/internal/codegen: typescript generation failed")

// tsConfig holds the resolved TypeScript-generation options.
type tsConfig struct {
	indent       string
	optionalType string // "" (undefined) or "null"
}

// TSOption configures TypeScript generation.
type TSOption func(*tsConfig)

// WithIndent sets the indentation string of the generated TypeScript. The
// default is two spaces, matching the JSON Schema marshaller (codegen.Marshal)
// so both generated artifacts share a house style.
func WithIndent(indent string) TSOption {
	return func(c *tsConfig) { c.indent = indent }
}

// WithNullOptional renders optional fields as `T | null` rather than the tygo
// default `field?: T` (`undefined`). Use it when the consuming UI deserializes
// JSON that carries explicit nulls for absent optional fields.
func WithNullOptional() TSOption {
	return func(c *tsConfig) { c.optionalType = "null" }
}

func resolveTSConfig(opts []TSOption) tsConfig {
	c := tsConfig{indent: "  "}
	for _, opt := range opts {
		opt(&c)
	}
	return c
}

// TypeScriptForSource converts a fragment of Go contract source — the type
// declarations of a contracts package — into deterministic TypeScript.
//
// goSource is ordinary Go source: a package clause is permitted and ignored,
// imports are stripped, and only top-level type/const declarations are
// converted (tygo reads the Go AST, not reflection, so doc comments, enums and
// constants survive — brief 06 §2.4). The returned bytes carry the
// Code-generated header and end with a trailing newline; identical input always
// yields byte-identical output, which is what makes the golden tests and the
// drift cross-check meaningful (RFC §6.2, brief 06 R1).
//
// On a tygo parse or convert failure the error wraps ErrTypeScriptGen.
//
// Malformed Go source — a struct field carrying a syntactically invalid struct
// tag is the known case — can drive the tygo dependency to panic rather than
// return an error (tygo parses tags via reflect.StructTag, which panics on a
// malformed pair). TypeScriptForSource contains that panic and converts it to
// an ErrTypeScriptGen error: a malformed contract file must fail the codegen
// step cleanly, never crash the process (CLAUDE.md §13 — never panic across a
// process boundary). Found by the Phase 21.5 FuzzTypeScriptForSource target.
func TypeScriptForSource(goSource string, opts ...TSOption) ([]byte, error) {
	cfg := resolveTSConfig(opts)

	decls, err := typeDeclSource(goSource)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrTypeScriptGen, err)
	}

	pc := tygo.PackageConfig{
		Path:             "contracts",
		Indent:           cfg.indent,
		PreserveComments: "default",
		EnumStyle:        "union",
	}
	if cfg.optionalType == "null" {
		pc.OptionalType = "null"
	}

	body, err := convertGoToTypeScript(decls, pc)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrTypeScriptGen, err)
	}

	return assembleTS(body), nil
}

// convertGoToTypeScript calls tygo.ConvertGoToTypescript under a recover guard:
// tygo panics (rather than returning an error) on some malformed input — a
// struct field with a syntactically invalid struct tag is the known case. The
// recover turns such a panic into an ordinary error so the caller's
// `%w: ErrTypeScriptGen` wrapping holds for every failure mode.
func convertGoToTypeScript(decls string, pc tygo.PackageConfig) (body string, err error) {
	defer func() {
		if r := recover(); r != nil {
			body = ""
			err = fmt.Errorf("tygo conversion panicked on malformed input: %v", r)
		}
	}()
	return tygo.ConvertGoToTypescript(decls, pc)
}

// TypeScriptForDir reads the .go files of a contracts directory and generates
// TypeScript for the type declarations they contain. It is the seam Phase 18's
// `dockyard generate` calls with a project's `internal/contracts` directory.
//
// Files are read in sorted filename order and their type declarations
// concatenated in that order, so the generated output is deterministic
// regardless of filesystem iteration order. Test files (`_test.go`) and
// generated files are skipped.
func TypeScriptForDir(dir string, opts ...TSOption) ([]byte, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("%w: read dir %s: %w", ErrTypeScriptGen, dir, err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		n := e.Name()
		if !strings.HasSuffix(n, ".go") || strings.HasSuffix(n, "_test.go") {
			continue
		}
		names = append(names, n)
	}
	sort.Strings(names)
	if len(names) == 0 {
		return nil, fmt.Errorf("%w: no .go contract files in %s", ErrTypeScriptGen, dir)
	}

	var combined strings.Builder
	for _, n := range names {
		path := filepath.Join(dir, n)
		raw, readErr := os.ReadFile(path) //nolint:gosec // path is composed from a caller-supplied contracts dir
		if readErr != nil {
			return nil, fmt.Errorf("%w: read %s: %w", ErrTypeScriptGen, path, readErr)
		}
		decls, declErr := typeDeclSource(string(raw))
		if declErr != nil {
			return nil, fmt.Errorf("%w: %s: %w", ErrTypeScriptGen, path, declErr)
		}
		if strings.TrimSpace(decls) == "" {
			continue
		}
		if combined.Len() > 0 {
			combined.WriteString("\n")
		}
		combined.WriteString(decls)
	}
	if strings.TrimSpace(combined.String()) == "" {
		return nil, fmt.Errorf("%w: %s declares no contract types", ErrTypeScriptGen, dir)
	}
	return TypeScriptForSource(combined.String(), opts...)
}

// typeDeclSource parses Go source and re-renders only its top-level type and
// const declarations, dropping the package clause, imports, functions and
// variables. tygo's ConvertGoToTypescript expects a bare declaration fragment;
// passing it a full file with a package clause fails to parse, and passing it
// functions or imports produces noise. Re-printing through go/printer also
// normalises formatting, which keeps the generated TypeScript deterministic.
//
// Before re-rendering, embedded (anonymous) struct fields are flattened: an
// anonymous field whose type is another struct declared in the same source is
// replaced, in place, by that struct's fields (D-051). tygo otherwise emits an
// embedded type as a *named property* (`Base: Base;`), but the JSON Schema
// generator — and Go's own encoding/json — *inline* an embedded struct's
// fields. Flattening makes the TypeScript artifact agree with the schema and
// with the wire format the UI actually deserializes.
func typeDeclSource(goSource string) (string, error) {
	src := goSource
	// A bare fragment (no package clause) is not a valid Go file; wrap it so the
	// parser accepts it. A real package clause is left in place and dropped below.
	if !hasPackageClause(src) {
		src = "package contracts\n\n" + src
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "contracts.go", src, parser.ParseComments)
	if err != nil {
		return "", fmt.Errorf("parse contract source: %w", err)
	}

	flattenEmbeddedStructs(file)

	var out bytes.Buffer
	pcfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue // skip funcs
		}
		if gen.Tok != token.TYPE && gen.Tok != token.CONST {
			continue // skip imports and vars
		}
		if out.Len() > 0 {
			out.WriteString("\n\n")
		}
		if err := pcfg.Fprint(&out, fset, gen); err != nil {
			return "", fmt.Errorf("render declaration: %w", err)
		}
	}
	return out.String(), nil
}

// flattenEmbeddedStructs rewrites every struct type declared in file so that
// each embedded (anonymous) field referencing another locally declared struct
// is replaced by that struct's own fields (D-051).
//
// The rewrite matches Go's encoding/json semantics:
//   - An embedded struct's fields are promoted into the embedding struct.
//   - A field of the outer struct shadows a promoted field of the same JSON
//     name ("outer wins"); the promoted duplicate is dropped.
//   - Promotion is transitive: an embedded struct that itself embeds another is
//     flattened first, so its already-promoted fields carry through.
//
// Only embedded *structs declared in the same source* are flattened — an
// embedded type from another package (e.g. an SDK type) is left as tygo's
// named property, since its fields are not visible here. Embedded named types
// of a non-struct kind are likewise left untouched.
func flattenEmbeddedStructs(file *ast.File) {
	structs := make(map[string]*ast.StructType)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			if st, ok := ts.Type.(*ast.StructType); ok {
				structs[ts.Name.Name] = st
			}
		}
	}
	done := make(map[string]bool)
	for name := range structs {
		flattenStruct(name, structs, done, make(map[string]bool))
	}
}

// flattenStruct flattens one named struct in place, recursing into any embedded
// struct first so promotion is transitive. inProgress guards a defensive cycle
// (a recursive struct never reaches the TypeScript path with a schema, but the
// guard keeps this walk total regardless).
func flattenStruct(name string, structs map[string]*ast.StructType, done, inProgress map[string]bool) {
	if done[name] || inProgress[name] {
		return
	}
	st := structs[name]
	if st == nil || st.Fields == nil {
		done[name] = true
		return
	}
	inProgress[name] = true

	flattened := make([]*ast.Field, 0, len(st.Fields.List))
	for _, f := range st.Fields.List {
		embeddedName, ok := embeddedStructName(f)
		if !ok {
			flattened = append(flattened, f)
			continue
		}
		if _, isLocalStruct := structs[embeddedName]; !isLocalStruct {
			// Embedded type is not a locally declared struct — leave it for tygo.
			flattened = append(flattened, f)
			continue
		}
		flattenStruct(embeddedName, structs, done, inProgress)
		flattened = append(flattened, structs[embeddedName].Fields.List...)
	}

	// Apply "outer wins": a later field with the same JSON name shadows an
	// earlier (promoted) one. Walk back-to-front, keeping the last occurrence.
	seen := make(map[string]bool)
	deduped := make([]*ast.Field, 0, len(flattened))
	for i := len(flattened) - 1; i >= 0; i-- {
		key := fieldJSONKey(flattened[i])
		if key != "" && seen[key] {
			continue
		}
		if key != "" {
			seen[key] = true
		}
		deduped = append(deduped, flattened[i])
	}
	for l, r := 0, len(deduped)-1; l < r; l, r = l+1, r-1 {
		deduped[l], deduped[r] = deduped[r], deduped[l]
	}

	st.Fields.List = deduped
	inProgress[name] = false
	done[name] = true
}

// embeddedStructName returns the type name of an embedded (anonymous) field —
// unwrapping a leading pointer — and true when f is such a field. A field with
// explicit names, or an anonymous field of a non-ident type, returns false.
func embeddedStructName(f *ast.Field) (string, bool) {
	if len(f.Names) != 0 {
		return "", false
	}
	expr := f.Type
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}
	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name, true
	}
	return "", false
}

// fieldJSONKey returns the JSON property name a struct field renders to — the
// `json` tag name when present and non-empty, otherwise the Go field name. It
// returns "" for an embedded field that survived flattening (no JSON identity
// to dedupe on) or a `json:"-"` field.
func fieldJSONKey(f *ast.Field) string {
	if len(f.Names) == 0 {
		return ""
	}
	goName := f.Names[0].Name
	if f.Tag == nil {
		return goName
	}
	// f.Tag.Value is the raw literal including its back-quotes; reflect.StructTag
	// expects the unquoted tag body.
	tag := reflect.StructTag(strings.Trim(f.Tag.Value, "`")).Get("json")
	if tag == "" {
		return goName
	}
	name := tag
	if i := strings.IndexByte(tag, ','); i >= 0 {
		name = tag[:i]
	}
	switch name {
	case "-":
		return ""
	case "":
		return goName
	default:
		return name
	}
}

// hasPackageClause reports whether src already opens with a `package` clause,
// ignoring leading comments and blank lines.
func hasPackageClause(src string) bool {
	for _, line := range strings.Split(src, "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "//") || strings.HasPrefix(t, "/*") {
			continue
		}
		return strings.HasPrefix(t, "package ")
	}
	return false
}

// assembleTS prepends the Code-generated header to a tygo-rendered body and
// guarantees exactly one trailing newline, for a stable on-disk form.
func assembleTS(body string) []byte {
	var buf bytes.Buffer
	buf.WriteString(generatedTSHeader)
	buf.WriteString("\n")
	buf.WriteString(strings.TrimRight(body, "\n"))
	buf.WriteString("\n")
	return buf.Bytes()
}
