// VitePress configuration for the Dockyard tech-docs site (Phase 29, D-137).
//
// Static markdown-first generator; same Vite toolchain the project already
// uses for web/ projects, so the install + build story has no new runtime
// dependency. GitHub Pages deploys the built site from .github/workflows/
// docs.yml.
//
// The `base` URL is the GitHub Pages path; we read DOCS_BASE from the
// environment so the CI workflow can pin it to "/dockyard/" without
// hard-coding the repo name in the config (the same project might be
// renamed or moved, and the build should not flip).
import { defineConfig } from "vitepress";

const base = process.env.DOCS_BASE ?? "/";

export default defineConfig({
  base,
  lang: "en-US",
  title: "Dockyard",
  description:
    "Dockyard — the Go-native framework for production-grade MCP Servers and MCP Apps.",
  cleanUrls: true,
  // The site fails the build on a dead internal link. Surfacing a 404
  // before publish is the whole point of having a docs build step in CI.
  ignoreDeadLinks: false,
  // Source files live under docs/site/. Reference files (RFC, plans,
  // glossary, decisions, design conventions) sit one level up; they are
  // mirrored into pages here via `reference/*.md` stubs that include the
  // canonical file. That keeps the build self-contained.
  themeConfig: {
    siteTitle: "Dockyard",
    nav: [
      { text: "Get started", link: "/getting-started/" },
      { text: "Guides", link: "/guides/contracts" },
      { text: "CLI", link: "/cli/" },
      { text: "Agent Skills", link: "/agent-skills/" },
      {
        text: "Reference",
        items: [
          { text: "RFC-001", link: "/reference/rfc" },
          { text: "Master plan", link: "/reference/master-plan" },
          { text: "Decisions log", link: "/reference/decisions" },
          { text: "Glossary", link: "/reference/glossary" },
          { text: "Design conventions", link: "/reference/design-conventions" },
        ],
      },
    ],
    sidebar: {
      "/getting-started/": [
        {
          text: "Get started",
          items: [
            { text: "Overview", link: "/getting-started/" },
            { text: "analytics-widgets walkthrough", link: "/getting-started/analytics-widgets" },
            { text: "approval-flows walkthrough", link: "/getting-started/approval-flows" },
            { text: "Worked examples", link: "/getting-started/examples" },
          ],
        },
      ],
      "/guides/": [
        {
          text: "Guides",
          items: [
            { text: "Contracts (Design A)", link: "/guides/contracts" },
            { text: "UI resources (MCP Apps)", link: "/guides/ui-resources" },
            { text: "Dev loop", link: "/guides/dev-loop" },
            { text: "Validate + test", link: "/guides/validate" },
            { text: "OAuth protected resource", link: "/guides/oauth-protected-resource" },
            { text: "Packaging + install", link: "/guides/packaging" },
            { text: "Inspector", link: "/guides/inspector" },
          ],
        },
      ],
      "/cli/": [
        {
          text: "CLI reference",
          items: [{ text: "Command tree", link: "/cli/" }],
        },
      ],
      "/agent-skills/": [
        {
          text: "Agent Skills (SKILL.md)",
          items: [{ text: "Index", link: "/agent-skills/" }],
        },
      ],
      "/reference/": [
        {
          text: "Reference",
          items: [
            { text: "RFC-001 — Dockyard", link: "/reference/rfc" },
            { text: "Master phase plan", link: "/reference/master-plan" },
            { text: "Decisions log", link: "/reference/decisions" },
            { text: "Glossary", link: "/reference/glossary" },
            { text: "Design conventions", link: "/reference/design-conventions" },
          ],
        },
      ],
    },
    socialLinks: [
      { icon: "github", link: "https://github.com/hurtener/dockyard" },
    ],
    footer: {
      message: "Apache-2.0 licensed — see LICENSE.",
      copyright: "© Dockyard contributors. Generated by VitePress (D-137).",
    },
    outline: { level: [2, 3] },
    search: { provider: "local" },
  },
  vite: {
    // VitePress's default behaviour is fine; we override nothing here.
    // The block is reserved for a future asset-handling tweak when the
    // docs grow images or PDFs not under public/.
  },
});
