// Package contracts holds this server's tool input and output contracts —
// the typed Go structs that are the source of truth for the tool schemas
// (Dockyard P1 — contract-first, RFC §6). The JSON Schema and TypeScript
// alongside these structs are GENERATED by `dockyard generate`; never
// hand-edit a generated file. Change a contract here, then regenerate.
//
// The approval-flows template ships two contract pairs:
//   - request_approval     — a generic approve/reject card.
//   - propose_with_edits   — a structured form whose proposed values are
//     user-editable.
//
// Each output carries a `Kind` discriminator so the App's single
// dispatcher can route `structuredContent` to the right renderer
// (approval card / edits form) without sniffing the shape — the same
// pattern the analytics-widgets template uses.
package contracts

import "time"

// ---------------------------------------------------------------------------
// request_approval — pause for human approval of a single decision.
// ---------------------------------------------------------------------------

// RequestApprovalInput is the model-facing input contract for
// request_approval. The model decides what to ask the human and supplies
// the prompt; the App renders it and pauses the task until the user
// approves or rejects.
type RequestApprovalInput struct {
	// Title is the one-line headline of the prompt — what the user sees
	// first. Required; a missing title drives the App's empty state.
	Title string `json:"title"`
	// Description is the full prompt body (paragraphs allowed); the App
	// renders it under the title.
	Description string `json:"description"`
	// Category is a short tag the App renders as a StatusChip
	// (e.g. "publishing", "billing", "security"). Optional.
	Category string `json:"category,omitempty"`
	// Metadata is an opaque, free-shape JSON object the App renders as a
	// key/value table for context (e.g. {"subscribers": 1247, "since":
	// "Mon 09:00"}). Optional.
	Metadata map[string]any `json:"metadata,omitempty"`
}

// RequestApprovalOutput is the structured payload the App's approval
// renderer consumes when the task resumes. It carries the prompt back
// through Title / Description / Category / Metadata (the App is a pure
// View — the model decides what to ask; the App renders what arrives)
// and carries the user's decision when one has been made.
//
// The lifecycle: `CreateTaskResult` flows first (a Tasks-aware host
// renders this output's State="awaiting" while the task is in
// input_required); when the user decides, the handler resumes and the
// terminal `tool-result` carries State="approved" or State="rejected"
// with the decision payload.
type RequestApprovalOutput struct {
	// Kind is always "approval" for a request_approval output. The
	// App's dispatcher reads it to route to the approval renderer.
	Kind string `json:"kind"`
	// TaskID is the id of the task the App is answering — stamped by
	// the handler when the task is created so the App's
	// elicitation-response post carries the right id. Empty when no
	// task was created (the capability-degraded path).
	TaskID string `json:"task_id,omitempty"`
	// Title is the prompt headline, passed through.
	Title string `json:"title"`
	// Description is the prompt body, passed through.
	Description string `json:"description"`
	// Category is the prompt tag, passed through (empty when not set).
	Category string `json:"category,omitempty"`
	// Metadata is the context payload, passed through.
	Metadata map[string]any `json:"metadata,omitempty"`
	// State is the UI state the App enters:
	//   "awaiting"   — the App should render the prompt and the
	//                  Approve / Reject buttons (the input_required
	//                  status; the App receives this in the first
	//                  push, before the user has decided);
	//   "approved"   — the user approved; the App renders the
	//                  decision summary;
	//   "rejected"   — the user rejected;
	//   "empty"      — the prompt itself was empty (no title);
	//   "error"      — the handler hit an error;
	//   "permission" — the requestor was not authorized.
	State string `json:"state"`
	// Approved carries the user's decision when State is "approved"
	// or "rejected"; nil otherwise.
	Approved *bool `json:"approved,omitempty"`
	// Reason is the user's optional free-text reason for the
	// decision; only meaningful when State is "approved" or
	// "rejected".
	Reason string `json:"reason,omitempty"`
	// DecidedAt is the timestamp the decision was recorded; zero
	// when State is not terminal.
	DecidedAt time.Time `json:"decided_at,omitempty"`
	// Message is the human-readable line rendered in non-ready
	// states (e.g. "Not authorized to approve this.", "The request
	// was empty.").
	Message string `json:"message,omitempty"`
}

// ---------------------------------------------------------------------------
// propose_with_edits — propose a structured change for review.
// ---------------------------------------------------------------------------

// FieldType is one of the V1 field types the App's form renderer
// supports natively. An unrecognised type renders as a plain text input
// (the App's FieldDiff falls back to text — forward-compat).
type FieldType string

const (
	// FieldTypeString is a single-line text input.
	FieldTypeString FieldType = "string"
	// FieldTypeNumber is a numeric input (integer or float).
	FieldTypeNumber FieldType = "number"
	// FieldTypeBoolean is a checkbox.
	FieldTypeBoolean FieldType = "boolean"
	// FieldTypeEnum is a select; the field must carry Options.
	FieldTypeEnum FieldType = "enum"
	// FieldTypeText is a multi-line text area.
	FieldTypeText FieldType = "text"
)

// FieldOption is one option for a FieldTypeEnum field. The Value reaches
// the handler verbatim; Label is the human-readable rendering.
type FieldOption struct {
	Value string `json:"value"`
	Label string `json:"label"`
}

// Field is one field of a propose_with_edits proposal. Each field
// carries the current value (read-only on the App side) paired with
// the proposed value (editable on the App side). The user's final
// choice for the field — proposed verbatim, or edited — is what the
// handler receives in the elicitation response.
type Field struct {
	// Key is the field identifier the handler keys decisions on. The
	// elicitation response maps Key → final value.
	Key string `json:"key"`
	// Label is the human-readable field name.
	Label string `json:"label"`
	// Type is the field's value type (V1: string/number/boolean/enum/text).
	Type FieldType `json:"type"`
	// Current is the value the system holds today (read-only on the
	// App).
	Current any `json:"current"`
	// Proposed is the value the model is suggesting; the App pre-fills
	// the editable input with it, and the user may edit it before
	// approving.
	Proposed any `json:"proposed"`
	// Options is the allowed-value set when Type is "enum"; ignored
	// for other types.
	Options []FieldOption `json:"options,omitempty"`
	// HelperText is rendered as small text under the input
	// (e.g. "ISO-4217 currency code").
	HelperText string `json:"helper_text,omitempty"`
}

// ProposeWithEditsInput is the model-facing input contract for
// propose_with_edits. The model supplies the title, description, and
// the list of fields; the App renders a form, the user edits any
// proposed value, then approves or rejects.
type ProposeWithEditsInput struct {
	// Title is the headline of the proposed change.
	Title string `json:"title"`
	// Description is the change's full body / context.
	Description string `json:"description"`
	// Fields are the editable fields of the proposal. An empty list
	// drives the App's empty state — there is nothing to review.
	Fields []Field `json:"fields"`
	// Category is a short tag the App renders as a StatusChip.
	Category string `json:"category,omitempty"`
}

// ProposeWithEditsOutput is the structured payload the App's edits
// renderer consumes. It mirrors the input through to the App and
// carries the user's decision and final edited values when one has
// been made.
type ProposeWithEditsOutput struct {
	// Kind is always "proposal" for a propose_with_edits output.
	Kind string `json:"kind"`
	// TaskID is the id of the task the App is answering — see the
	// RequestApprovalOutput.TaskID comment.
	TaskID string `json:"task_id,omitempty"`
	// Title is the proposal headline, passed through.
	Title string `json:"title"`
	// Description is the proposal body, passed through.
	Description string `json:"description"`
	// Fields are the proposal fields, passed through.
	Fields []Field `json:"fields"`
	// Category is the proposal tag, passed through (empty when not
	// set).
	Category string `json:"category,omitempty"`
	// State is the UI state the App enters:
	//   "awaiting"   — render the form and the Approve / Reject buttons;
	//   "approved"   — the user approved; the App renders the final
	//                  edited values;
	//   "rejected"   — the user rejected;
	//   "empty"      — no fields to review;
	//   "error"      — the handler hit an error;
	//   "permission" — the requestor was not authorized.
	State string `json:"state"`
	// Approved carries the user's decision when terminal.
	Approved *bool `json:"approved,omitempty"`
	// Edits maps a field's Key to its final value — the proposed
	// value verbatim, or the user's edit. Only populated when
	// Approved is true.
	Edits map[string]any `json:"edits,omitempty"`
	// Reason is the user's optional free-text reason for the decision.
	Reason string `json:"reason,omitempty"`
	// DecidedAt is the timestamp the decision was recorded.
	DecidedAt time.Time `json:"decided_at,omitempty"`
	// Message is the human-readable line rendered in non-ready states.
	Message string `json:"message,omitempty"`
}

// ---------------------------------------------------------------------------
// Shared elicitation-response shape — what the App posts back.
// ---------------------------------------------------------------------------

// ApprovalReply is the App-supplied reply the handlers decode out of
// the elicitation response. The App posts this verbatim through the
// bridge's `sendElicitationResponse` View helper; the
// `TaskHandle.RequireInput` body unmarshals it.
//
// This is the contract between the App and the handler — not part of
// the model-facing tool I/O contract. Distinct from RequestApprovalOutput
// / ProposeWithEditsOutput because the reply may be a subset (a reject
// reply carries no edits) and is shaped for the handler to decide on,
// not for the model to consume.
type ApprovalReply struct {
	// Approved is the user's verdict — true for approve, false for
	// reject.
	Approved bool `json:"approved"`
	// Reason is the user's optional free-text reason.
	Reason string `json:"reason,omitempty"`
	// Edits is the final field values, for a propose_with_edits
	// approval. Nil for request_approval.
	Edits map[string]any `json:"edits,omitempty"`
}
