package scaffold

import (
	"fmt"
	"regexp"
	"strings"
)

// This file holds the scaffolded project's file templates. Every renderer is a
// pure function of Options, so Generate is deterministic (the golden test
// depends on it). The templates are deliberately boring and readable — RFC §6:
// "generated code teams are happy to own".

// dockyardModule is the import path of the Dockyard runtime library a
// scaffolded project depends on.
const dockyardModule = "github.com/hurtener/dockyard"

// goVersion is the Go toolchain version pinned in a scaffolded go.mod —
// matched to the framework's own pin (CLAUDE.md §5, brief 06).
const goVersion = "1.26.2"

// renderManifest renders dockyard.app.yaml — the no-template blank server
// manifest (RFC §4.2): one tool, no apps block (a plain MCP server has no UI,
// RFC §4.1), stdio transport. The quality block keeps the contract-test and
// fixture gates on; the UI-state gates are off because a no-template server
// ships no UI.
func renderManifest(o Options) string {
	return fmt.Sprintf(`# Dockyard manifest — the control plane for this MCP server (RFC §4.2).
# Generated by 'dockyard new'. Edit freely; 'dockyard validate' checks it.
name: %s
title: %s
version: 0.1.0

runtime:
  # Deployment modes this server supports. stdio is the local single-user
  # mode; add 'http' to also serve the streamable-HTTP transport.
  transports: [stdio]

tools:
  - name: greet
    description: Greet a person by name and return the assembled greeting.
    # input/output are Go type references — the contract-first source of
    # truth (P1, RFC §6). Their JSON Schema is generated, never hand-written.
    input: internal/contracts.GreetInput
    output: internal/contracts.GreetOutput
    # task_support declares the tool's relationship to the MCP Tasks
    # extension (RFC §8.4). forbidden = the tool always runs synchronously;
    # optional = the runtime may run it as a task; required = it always runs
    # as a task. When at least one tool declares optional or required,
    # the scaffold's main.go constructs a tasks.Engine and attaches it via
    # server.Options{Tasks: engine} — dockyard new does this for you.
    task_support: %s

# A no-template server ships no UI, so there is no apps[] block. Attach a
# Svelte UI later with 'dockyard new --template' or by adding an apps[] entry.

quality:                  # RFC §9.4 — enforced by 'dockyard validate'.
  # UI-state gates are off: this server has no UI to require states of.
  require_loading_state: false
  require_empty_state: false
  require_error_state: false
  require_permission_state: false
  # require_contract_tests applies to every server (the project must carry a
  # contract test); require_fixtures is UI-scoped (it requires inspector
  # fixtures for UI-bearing tools only — this server has none, so it is a
  # no-op until you attach a UI). Both are enforced by 'dockyard validate'.
  require_fixtures: true
  require_contract_tests: true
  require_spec_compliance: true
`, o.Name, titleCase(o.Name), o.taskSupport())
}

// renderGoMod renders the scaffolded project's go.mod. It requires the
// Dockyard runtime library; when DockyardReplace is set (the pre-release
// workflow — the framework is not yet published to a module registry) a
// replace directive points the import at a local checkout so the scaffold
// compiles. A released Dockyard drops the replace.
func renderGoMod(o Options) string {
	var b strings.Builder
	fmt.Fprintf(&b, "module %s\n\n", o.modulePath())
	fmt.Fprintf(&b, "go %s\n\n", goVersion)
	fmt.Fprintf(&b, "require %s %s\n", dockyardModule, requireVersion(o.DockyardVersion))
	if o.DockyardReplace != "" {
		fmt.Fprintf(&b, "\nreplace %s => %s\n", dockyardModule, o.DockyardReplace)
	}
	return b.String()
}

// releaseVersionRE matches a release-shaped module version (major.minor.patch,
// optional v-prefix, optional pre-release / build metadata).
var releaseVersionRE = regexp.MustCompile(`^v?\d+\.\d+\.\d+([-+].*)?$`)

// requireVersion is the version the scaffolded go.mod pins for the Dockyard
// module. A real release version (vX.Y.Z — normally the scaffolding CLI's own
// version) is pinned so a project that drops the local `replace` resolves the
// published module from the proxy without a hand edit (the v1.3 fix for the
// `v0.0.0: unknown revision` sharp edge). Anything else — empty, or the
// `0.0.0-dev` placeholder a `go build` / `make build` carries — falls back to
// `v0.0.0`, which is only ever resolved through the `replace` directive (the
// build-from-source path).
func requireVersion(v string) string {
	v = strings.TrimSpace(v)
	if v == "" || v == "0.0.0-dev" || v == "(devel)" || !releaseVersionRE.MatchString(v) {
		return "v0.0.0"
	}
	if !strings.HasPrefix(v, "v") {
		v = "v" + v
	}
	return v
}

// RequireVersion is the exported face of requireVersion for the builtin
// template packages (analyticswidgets, approvalflows), which live outside this
// package and so cannot reach the unexported helper. A template's go.mod.tmpl
// carries a __DOCKYARD_VERSION__ token that resolves to this value — the same
// version-pin logic the blank scaffold's renderGoMod applies — so a released
// CLI scaffolding a template pins the real release version (not the v0.0.0
// placeholder) and `go mod tidy` resolves the published module flag-free.
func RequireVersion(v string) string { return requireVersion(v) }

// WebDepSpecs returns the npm dependency specs a scaffolded project's
// web/package.json uses for dockyard-bridge and dockyard-ui — the values the
// __DOCKYARD_BRIDGE_SPEC__ / __DOCKYARD_UI_SPEC__ tokens resolve to. The two
// UI templates share this one resolver so the consume-side policy lives in one
// place.
//
// With DockyardWebPath set (the --dockyard-path build-from-source workflow) it
// points each at the local Dockyard checkout via a file: spec. Otherwise it
// pins the published packages with a caret range derived from the CLI's
// resolved version — so a --template scaffold's web/ `npm install` resolves
// dockyard-bridge / dockyard-ui from npm with no --dockyard-path and no local
// checkout (v1.3 wave B — D-172; the @dockyard/* packages now publish under the
// repo version, D-172). A dev CLI carrying no real version falls back to "*"
// (latest published) — a corner case, since a dev build uses --dockyard-path.
func WebDepSpecs(opts Options) (bridge, ui string) {
	if opts.DockyardWebPath != "" {
		return "file:" + opts.DockyardWebPath + "/bridge",
			"file:" + opts.DockyardWebPath + "/ui"
	}
	spec := npmCaretVersion(opts.DockyardVersion)
	return spec, spec
}

// npmCaretVersion turns the CLI's resolved version into the npm caret range the
// scaffold pins for the @dockyard/* frontend packages. A real release version
// (vX.Y.Z) becomes "^X.Y.Z" (npm specs carry no leading v); anything else — the
// 0.0.0-dev placeholder a checkout build carries — falls back to "*".
func npmCaretVersion(v string) string {
	v = strings.TrimSpace(v)
	if v == "" || v == "0.0.0-dev" || v == "(devel)" || !releaseVersionRE.MatchString(v) {
		return "*"
	}
	return "^" + strings.TrimPrefix(v, "v")
}

// renderMainGo renders main.go — the runnable entrypoint. It constructs a
// Dockyard server, registers the example tool, and serves the transport
// selected by the DOCKYARD_TRANSPORT environment variable. The blank scaffold's
// acceptance bar is "builds and serves": this is the file that makes it serve
// (RFC §9.1).
//
// DOCKYARD_TRANSPORT is the contract `dockyard run` uses to tell a server which
// transport to bring up: "stdio" (the local single-user mode, the default when
// the variable is unset) or "http" (the streamable-HTTP service mode). Reading
// it here means `dockyard run --transport http` genuinely serves HTTP without
// the developer touching main.go.
//
// The renderer branches on whether the manifest declares any task-supporting
// tool (D-164): when it does, the rendered main.go constructs a real
// tasks.Engine over an in-memory TaskStore and attaches it via
// server.Options{Tasks: engine} so the server's stdio + HTTP transports
// intercept tasks/* JSON-RPC frames and route them into the engine. When
// no tool declares task support, the rendered main.go skips the engine
// construction entirely — zero overhead, zero new dependencies.
func renderMainGo(o Options) string {
	if o.wireTasksEngine() {
		return renderMainGoWithTasks(o)
	}
	return renderMainGoPlain(o)
}

// renderMainGoPlain renders the engine-free shape of main.go — the
// historical default. It is the rendered output when no tool in the
// manifest declares task_support: optional or required.
func renderMainGoPlain(o Options) string {
	return fmt.Sprintf(`// Command %s is an MCP server scaffolded by 'dockyard new'.
//
// It registers one example tool ("greet") and serves the MCP protocol. The
// transport is chosen by the DOCKYARD_TRANSPORT environment variable — "stdio"
// (the default: the local, single-user transport) or "http" (the
// streamable-HTTP service mode). 'dockyard run --transport http' sets it for
// you; you can also set it by hand. Wire the server into an MCP host (Claude,
// Cursor, …) with 'dockyard install'.
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"

	"%s/runtime/server"
)

// httpAddr is the address the HTTP transport listens on when
// DOCKYARD_TRANSPORT=http. DOCKYARD_HTTP_ADDR overrides it.
const httpAddr = "127.0.0.1:8080"

func main() {
	// A text slog handler — readable local logs (Dockyard convention).
	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))

	// Serve until the process is interrupted (Ctrl-C) or the host closes the
	// transport.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	srv, err := server.New(server.Info{
		Name:    %q,
		Title:   %q,
		Version: "0.1.0",
	}, &server.Options{Logger: logger})
	if err != nil {
		logger.Error("create server", slog.String("error", err.Error()))
		os.Exit(1)
	}

	if err := registerTools(srv); err != nil {
		logger.Error("register tools", slog.String("error", err.Error()))
		os.Exit(1)
	}

	if err := serve(ctx, srv, logger); err != nil {
		logger.Error("serve", slog.String("error", err.Error()))
		os.Exit(1)
	}
}

// serve brings up the transport named by DOCKYARD_TRANSPORT. An unset or
// "stdio" value serves stdio; "http" serves the streamable-HTTP transport. An
// unrecognised value is a clean, explained failure rather than a silent
// fallback.
func serve(ctx context.Context, srv *server.Server, logger *slog.Logger) error {
	switch transport := os.Getenv("DOCKYARD_TRANSPORT"); transport {
	case "", "stdio":
		return srv.ServeStdio(ctx)
	case "http":
		return serveHTTP(ctx, srv, logger)
	default:
		return errors.New("unsupported DOCKYARD_TRANSPORT " + transport + " (want \"stdio\" or \"http\")")
	}
}

// serveHTTP serves the streamable-HTTP transport. The HTTP security posture is
// the runtime's secure default — DNS-rebinding and cross-origin protection both
// on (runtime/server.DefaultHTTPSecurity). The listen address is httpAddr,
// overridable with DOCKYARD_HTTP_ADDR.
func serveHTTP(ctx context.Context, srv *server.Server, logger *slog.Logger) error {
	handler, err := srv.HTTPHandler(nil)
	if err != nil {
		return err
	}
	addr := httpAddr
	if override := os.Getenv("DOCKYARD_HTTP_ADDR"); override != "" {
		addr = override
	}
	httpSrv := &http.Server{Addr: addr, Handler: handler}
	go func() {
		<-ctx.Done()
		_ = httpSrv.Close()
	}()
	logger.Info("serving streamable-HTTP transport", slog.String("addr", addr))
	if err := httpSrv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		return err
	}
	return nil
}
`, o.Name, dockyardModule, o.Name, titleCase(o.Name))
}

// renderMainGoWithTasks renders the engine-wired shape of main.go (D-164).
// It is the rendered output when at least one tool in the manifest declares
// task_support: optional or required.
//
// The differences from the plain shape are intentionally local:
//
//   - imports add runtime/tasks
//   - main constructs `taskStore := tasks.NewInMemoryStore()` and
//     `engine, err := tasks.NewEngine(taskStore, &tasks.Options{...})`
//   - `engine.StartSweep(ctx)` runs the purge sweep for the process
//     lifetime; `defer engine.StopSweep()` joins it on shutdown
//   - server.Options carries `Tasks: engine` — the server's stdio and HTTP
//     transports now intercept tasks/* JSON-RPC frames and route them
//     into the engine (RFC §8.2)
//
// The Lifecycle defaults are intentionally conservative: MaxTTL 1h,
// DefaultTTL 5m, PurgeInterval 30s, MaxConcurrentPerRequestor 16. They
// match brief 02 §4.5/§4.6's "non-zero defaults, room for a single-user
// stdio workload" guidance. A developer with a different production
// posture edits main.go after scaffold.
//
// Stdio is single-user and unauthenticated: AdvertiseList stays off
// (brief 02 §4.5 — a receiver that cannot identify requestors must not
// advertise tasks/list). An HTTP deployment with real authentication
// sets RequestorIdentifiable: true and passes a TasksAuthContext on the
// server.Options.
func renderMainGoWithTasks(o Options) string {
	return fmt.Sprintf(`// Command %s is an MCP server scaffolded by 'dockyard new'.
//
// It registers one example tool (%q) and serves the MCP protocol. The
// transport is chosen by the DOCKYARD_TRANSPORT environment variable — "stdio"
// (the default: the local, single-user transport) or "http" (the
// streamable-HTTP service mode). 'dockyard run --transport http' sets it for
// you; you can also set it by hand. Wire the server into an MCP host (Claude,
// Cursor, …) with 'dockyard install'.
//
// The manifest declares at least one tool with task_support: optional or
// required, so the scaffold has auto-wired a tasks.Engine (D-164). The
// engine routes tasks/* JSON-RPC frames into a real lifecycle: a tool that
// runs as a task can pause for input_required, report progress, observe
// cooperative cancellation, and reach a terminal status (RFC §8.4). The
// in-memory TaskStore is correct for single-user stdio; replace it with
// runtime/store/sqlite for a durable HTTP/Portico deployment.
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"time"

	"%s/runtime/server"
	"%s/runtime/tasks"
)

// httpAddr is the address the HTTP transport listens on when
// DOCKYARD_TRANSPORT=http. DOCKYARD_HTTP_ADDR overrides it.
const httpAddr = "127.0.0.1:8080"

func main() {
	// A text slog handler — readable local logs (Dockyard convention).
	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))

	// Serve until the process is interrupted (Ctrl-C) or the host closes the
	// transport.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	// --- the Tasks engine (D-164) -----------------------------------------
	//
	// The manifest declares at least one tool with task_support: optional
	// or required, so the scaffold has wired a real tasks.Engine over an
	// in-memory TaskStore and attached it via server.Options{Tasks: engine}.
	// The Lifecycle defaults below are conservative; tune them in your
	// manifest's tasks: block, or edit Options here for a different
	// production posture.
	//
	// In-memory store. For single-user stdio the in-memory store is
	// correct: tasks live as long as the process. For a production HTTP
	// deployment, replace with sqlitestore.Open + the engine's migration
	// step. The contract is the tasks.TaskStore seam — the engine works
	// against either driver.
	taskStore := tasks.NewInMemoryStore()
	engine, err := tasks.NewEngine(taskStore, &tasks.Options{
		Logger: logger,
		// Stdio is single-user and unauthenticated: tasks/list is not
		// advertised (brief 02 §4.5). An HTTP deployment with real auth
		// should set RequestorIdentifiable: true and pass a
		// TasksAuthContext on the server.Options below.
		RequestorIdentifiable: false,
		AdvertiseList:         false,
		PollInterval:          250,
		Lifecycle: tasks.Lifecycle{
			MaxTTL:                    1 * time.Hour,
			DefaultTTL:                5 * time.Minute,
			PurgeInterval:             30 * time.Second,
			MaxConcurrentPerRequestor: 16,
		},
	})
	if err != nil {
		logger.Error("create tasks engine", slog.String("error", err.Error()))
		os.Exit(1)
	}
	// Start the TTL purge sweep; Stop joins it on shutdown.
	engine.StartSweep(ctx)
	defer engine.StopSweep()

	srv, err := server.New(server.Info{
		Name:    %q,
		Title:   %q,
		Version: "0.1.0",
	}, &server.Options{
		Logger: logger,
		// Attach the Tasks engine — the server's stdio + HTTP transports
		// now intercept tasks/* JSON-RPC frames and route them into the
		// engine (RFC §8.2). The capabilities.tasks block is injected
		// into the initialize handshake response.
		Tasks: engine,
		// TasksAuthContext: nil — stdio is unauthenticated. For HTTP
		// with real auth, supply a function here that derives the
		// requestor's identity from the bearer token; the engine then
		// binds tasks to that context (RFC §8.5).
		TasksAuthContext: nil,
	})
	if err != nil {
		logger.Error("create server", slog.String("error", err.Error()))
		os.Exit(1)
	}

	if err := registerTools(srv); err != nil {
		logger.Error("register tools", slog.String("error", err.Error()))
		os.Exit(1)
	}

	if err := serve(ctx, srv, logger); err != nil {
		logger.Error("serve", slog.String("error", err.Error()))
		os.Exit(1)
	}
}

// serve brings up the transport named by DOCKYARD_TRANSPORT. An unset or
// "stdio" value serves stdio; "http" serves the streamable-HTTP transport. An
// unrecognised value is a clean, explained failure rather than a silent
// fallback.
func serve(ctx context.Context, srv *server.Server, logger *slog.Logger) error {
	switch transport := os.Getenv("DOCKYARD_TRANSPORT"); transport {
	case "", "stdio":
		return srv.ServeStdio(ctx)
	case "http":
		return serveHTTP(ctx, srv, logger)
	default:
		return errors.New("unsupported DOCKYARD_TRANSPORT " + transport + " (want \"stdio\" or \"http\")")
	}
}

// serveHTTP serves the streamable-HTTP transport. The HTTP security posture is
// the runtime's secure default — DNS-rebinding and cross-origin protection both
// on (runtime/server.DefaultHTTPSecurity). The listen address is httpAddr,
// overridable with DOCKYARD_HTTP_ADDR.
func serveHTTP(ctx context.Context, srv *server.Server, logger *slog.Logger) error {
	handler, err := srv.HTTPHandler(nil)
	if err != nil {
		return err
	}
	addr := httpAddr
	if override := os.Getenv("DOCKYARD_HTTP_ADDR"); override != "" {
		addr = override
	}
	httpSrv := &http.Server{Addr: addr, Handler: handler}
	go func() {
		<-ctx.Done()
		_ = httpSrv.Close()
	}()
	logger.Info("serving streamable-HTTP transport", slog.String("addr", addr))
	if err := httpSrv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		return err
	}
	return nil
}
`, o.Name, "greet", dockyardModule, dockyardModule, o.Name, titleCase(o.Name))
}

// renderGreetTool renders greet.go — the example contract-first tool. It shows
// the canonical shape: a typed handler over the GreetInput/GreetOutput
// contracts, declared with the runtime/tool builder, registered on the server.
func renderGreetTool(o Options) string {
	return fmt.Sprintf(`package main

import (
	"context"
	"strings"
	"unicode/utf8"

	"%s/runtime/server"
	"%s/runtime/tool"

	"%s/internal/contracts"
)

// registerTools declares and registers every tool this server exposes. main
// calls it once, before serving. Add a tool by writing its handler and one
// more Register call here.
func registerTools(srv *server.Server) error {
	// The 'greet' tool — the example tool 'dockyard new' scaffolds. It is
	// contract-first (P1, RFC §6): GreetInput and GreetOutput are typed Go
	// structs in internal/contracts; their JSON Schema is generated, and the
	// runtime validates an incoming call against it before greet runs.
	return tool.New[contracts.GreetInput, contracts.GreetOutput]("greet").
		Describe("Greet a person by name and return the assembled greeting.").
		Handler(greet).
		Register(srv)
}

// greet is the 'greet' tool's handler. It receives the decoded, schema-valid
// input and returns the typed output split: Text is model-facing, Structured
// is the typed, UI-facing payload (RFC §6.3).
func greet(_ context.Context, in contracts.GreetInput) (tool.Result[contracts.GreetOutput], error) {
	greeting := in.Greeting
	if strings.TrimSpace(greeting) == "" {
		greeting = "Hello"
	}
	message := greeting + ", " + in.Name + "!"
	return tool.Result[contracts.GreetOutput]{
		Text: message,
		Structured: contracts.GreetOutput{
			Message: message,
			Length:  utf8.RuneCountInString(message),
		},
	}, nil
}
`, dockyardModule, dockyardModule, o.modulePath())
}

// renderGreetTest renders greet_test.go — a contract test for the example
// tool. A scaffolded project ships with a passing test so 'go test' is green
// from the first minute and the contract-test quality gate has something to
// enforce (RFC §9.4).
func renderGreetTest(o Options) string {
	return fmt.Sprintf(`package main

import (
	"context"
	"testing"

	"%s/internal/contracts"
)

// TestGreet is the example tool's contract test. It exercises the handler
// directly — no transport, no server — which is the fast inner loop for a
// contract-first tool.
func TestGreet(t *testing.T) {
	tests := []struct {
		name    string
		in      contracts.GreetInput
		wantMsg string
	}{
		{
			name:    "default greeting",
			in:      contracts.GreetInput{Name: "Ada"},
			wantMsg: "Hello, Ada!",
		},
		{
			name:    "custom greeting",
			in:      contracts.GreetInput{Name: "Grace", Greeting: "Hi"},
			wantMsg: "Hi, Grace!",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			res, err := greet(context.Background(), tt.in)
			if err != nil {
				t.Fatalf("greet: %%v", err)
			}
			if res.Structured.Message != tt.wantMsg {
				t.Errorf("Message = %%q, want %%q", res.Structured.Message, tt.wantMsg)
			}
			if res.Structured.Length != len([]rune(tt.wantMsg)) {
				t.Errorf("Length = %%d, want %%d", res.Structured.Length, len([]rune(tt.wantMsg)))
			}
			if res.Text != tt.wantMsg {
				t.Errorf("Text = %%q, want %%q", res.Text, tt.wantMsg)
			}
		})
	}
}
`, o.modulePath())
}

// renderReadme renders the scaffolded project's README.md.
func renderReadme(o Options) string {
	return fmt.Sprintf("# %s\n\n"+
		"An MCP server scaffolded with [Dockyard](https://github.com/hurtener/dockyard).\n\n"+
		"## Layout\n\n"+
		"- `dockyard.app.yaml` — the manifest (server identity, tools, quality gates).\n"+
		"- `main.go` — the entrypoint: constructs the server, serves stdio.\n"+
		"- `greet.go` — the example `greet` tool and its handler.\n"+
		"- `greet_test.go` — a contract test for the example tool.\n"+
		"- `internal/contracts/` — the typed Go contract structs (the source of\n"+
		"  truth, P1) plus their **generated** JSON Schema and TypeScript. Never\n"+
		"  hand-edit a generated file; change the Go struct and regenerate.\n\n"+
		"## Run\n\n"+
		"```sh\n"+
		"go run .                          # serve over stdio (the default)\n"+
		"DOCKYARD_TRANSPORT=http go run .   # serve the streamable-HTTP transport\n"+
		"go test ./...                     # run the contract tests\n"+
		"```\n\n"+
		"## Next steps\n\n"+
		"- Add a tool: write a handler and a `tool.New(...)` call in `greet.go`.\n"+
		"- Edit a contract: change the struct in `internal/contracts`, then\n"+
		"  regenerate the schema with `dockyard generate`.\n"+
		"- Validate the project with `dockyard validate`.\n",
		titleCase(o.Name))
}

// gitignoreContent is the scaffolded project's .gitignore. Generated contract
// artifacts are intentionally NOT ignored — they are checked in so a clone
// builds without a generate step, and 'dockyard validate' diffs them.
const gitignoreContent = `# Build output
/bin/
/dist/

# Go test artifacts
*.test
coverage.out
`
