package scaffold

import (
	"fmt"
	"strings"
)

// This file holds the scaffolded project's file templates. Every renderer is a
// pure function of Options, so Generate is deterministic (the golden test
// depends on it). The templates are deliberately boring and readable — RFC §6:
// "generated code teams are happy to own".

// dockyardModule is the import path of the Dockyard runtime library a
// scaffolded project depends on.
const dockyardModule = "github.com/hurtener/dockyard"

// goVersion is the Go toolchain version pinned in a scaffolded go.mod —
// matched to the framework's own pin (CLAUDE.md §5, brief 06).
const goVersion = "1.26.2"

// renderManifest renders dockyard.app.yaml — the no-template blank server
// manifest (RFC §4.2): one tool, no apps block (a plain MCP server has no UI,
// RFC §4.1), stdio transport. The quality block keeps the contract-test and
// fixture gates on; the UI-state gates are off because a no-template server
// ships no UI.
func renderManifest(o Options) string {
	return fmt.Sprintf(`# Dockyard manifest — the control plane for this MCP server (RFC §4.2).
# Generated by 'dockyard new'. Edit freely; 'dockyard validate' checks it.
name: %s
title: %s
version: 0.1.0

runtime:
  # Deployment modes this server supports. stdio is the local single-user
  # mode; add 'http' to also serve the streamable-HTTP transport.
  transports: [stdio]

tools:
  - name: greet
    description: Greet a person by name and return the assembled greeting.
    # input/output are Go type references — the contract-first source of
    # truth (P1, RFC §6). Their JSON Schema is generated, never hand-written.
    input: internal/contracts.GreetInput
    output: internal/contracts.GreetOutput
    # This tool runs synchronously; it never becomes an MCP Task.
    task_support: forbidden

# A no-template server ships no UI, so there is no apps[] block. Attach a
# Svelte UI later with 'dockyard new --template' or by adding an apps[] entry.

quality:                  # RFC §9.4 — enforced by 'dockyard validate'.
  # UI-state gates are off: this server has no UI to require states of.
  require_loading_state: false
  require_empty_state: false
  require_error_state: false
  require_permission_state: false
  # Contract hygiene gates stay on — they apply to every server.
  require_fixtures: true
  require_contract_tests: true
  require_spec_compliance: true
`, o.Name, titleCase(o.Name))
}

// renderGoMod renders the scaffolded project's go.mod. It requires the
// Dockyard runtime library; when DockyardReplace is set (the pre-release
// workflow — the framework is not yet published to a module registry) a
// replace directive points the import at a local checkout so the scaffold
// compiles. A released Dockyard drops the replace.
func renderGoMod(o Options) string {
	var b strings.Builder
	fmt.Fprintf(&b, "module %s\n\n", o.modulePath())
	fmt.Fprintf(&b, "go %s\n\n", goVersion)
	fmt.Fprintf(&b, "require %s v0.0.0\n", dockyardModule)
	if o.DockyardReplace != "" {
		fmt.Fprintf(&b, "\nreplace %s => %s\n", dockyardModule, o.DockyardReplace)
	}
	return b.String()
}

// renderMainGo renders main.go — the runnable entrypoint. It constructs a
// Dockyard server, registers the example tool, and serves stdio. The blank
// scaffold's acceptance bar is "builds and serves": this is the file that
// makes it serve (RFC §9.1).
func renderMainGo(o Options) string {
	return fmt.Sprintf(`// Command %s is an MCP server scaffolded by 'dockyard new'.
//
// It registers one example tool ("greet") and serves the MCP protocol over
// stdio — the local, single-user transport. Run it directly, or wire it into
// an MCP host (Claude, Cursor, …) with 'dockyard install' once that lands.
package main

import (
	"context"
	"log/slog"
	"os"
	"os/signal"

	"%s/runtime/server"
)

func main() {
	// A text slog handler — readable local logs (Dockyard convention).
	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))

	// Serve until the process is interrupted (Ctrl-C) or the host closes the
	// stdio pipe.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	srv, err := server.New(server.Info{
		Name:    %q,
		Title:   %q,
		Version: "0.1.0",
	}, &server.Options{Logger: logger})
	if err != nil {
		logger.Error("create server", slog.String("error", err.Error()))
		os.Exit(1)
	}

	if err := registerTools(srv); err != nil {
		logger.Error("register tools", slog.String("error", err.Error()))
		os.Exit(1)
	}

	if err := srv.ServeStdio(ctx); err != nil {
		logger.Error("serve", slog.String("error", err.Error()))
		os.Exit(1)
	}
}
`, o.Name, dockyardModule, o.Name, titleCase(o.Name))
}

// renderGreetTool renders greet.go — the example contract-first tool. It shows
// the canonical shape: a typed handler over the GreetInput/GreetOutput
// contracts, declared with the runtime/tool builder, registered on the server.
func renderGreetTool(o Options) string {
	return fmt.Sprintf(`package main

import (
	"context"
	"strings"
	"unicode/utf8"

	"%s/runtime/server"
	"%s/runtime/tool"

	"%s/internal/contracts"
)

// registerTools declares and registers every tool this server exposes. main
// calls it once, before serving. Add a tool by writing its handler and one
// more Register call here.
func registerTools(srv *server.Server) error {
	// The 'greet' tool — the example tool 'dockyard new' scaffolds. It is
	// contract-first (P1, RFC §6): GreetInput and GreetOutput are typed Go
	// structs in internal/contracts; their JSON Schema is generated, and the
	// runtime validates an incoming call against it before greet runs.
	return tool.New[contracts.GreetInput, contracts.GreetOutput]("greet").
		Describe("Greet a person by name and return the assembled greeting.").
		Handler(greet).
		Register(srv)
}

// greet is the 'greet' tool's handler. It receives the decoded, schema-valid
// input and returns the typed output split: Text is model-facing, Structured
// is the typed, UI-facing payload (RFC §6.3).
func greet(_ context.Context, in contracts.GreetInput) (tool.Result[contracts.GreetOutput], error) {
	greeting := in.Greeting
	if strings.TrimSpace(greeting) == "" {
		greeting = "Hello"
	}
	message := greeting + ", " + in.Name + "!"
	return tool.Result[contracts.GreetOutput]{
		Text: message,
		Structured: contracts.GreetOutput{
			Message: message,
			Length:  utf8.RuneCountInString(message),
		},
	}, nil
}
`, dockyardModule, dockyardModule, o.modulePath())
}

// renderGreetTest renders greet_test.go — a contract test for the example
// tool. A scaffolded project ships with a passing test so 'go test' is green
// from the first minute and the contract-test quality gate has something to
// enforce (RFC §9.4).
func renderGreetTest(o Options) string {
	return fmt.Sprintf(`package main

import (
	"context"
	"testing"

	"%s/internal/contracts"
)

// TestGreet is the example tool's contract test. It exercises the handler
// directly — no transport, no server — which is the fast inner loop for a
// contract-first tool.
func TestGreet(t *testing.T) {
	tests := []struct {
		name    string
		in      contracts.GreetInput
		wantMsg string
	}{
		{
			name:    "default greeting",
			in:      contracts.GreetInput{Name: "Ada"},
			wantMsg: "Hello, Ada!",
		},
		{
			name:    "custom greeting",
			in:      contracts.GreetInput{Name: "Grace", Greeting: "Hi"},
			wantMsg: "Hi, Grace!",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			res, err := greet(context.Background(), tt.in)
			if err != nil {
				t.Fatalf("greet: %%v", err)
			}
			if res.Structured.Message != tt.wantMsg {
				t.Errorf("Message = %%q, want %%q", res.Structured.Message, tt.wantMsg)
			}
			if res.Structured.Length != len([]rune(tt.wantMsg)) {
				t.Errorf("Length = %%d, want %%d", res.Structured.Length, len([]rune(tt.wantMsg)))
			}
			if res.Text != tt.wantMsg {
				t.Errorf("Text = %%q, want %%q", res.Text, tt.wantMsg)
			}
		})
	}
}
`, o.modulePath())
}

// renderReadme renders the scaffolded project's README.md.
func renderReadme(o Options) string {
	return fmt.Sprintf("# %s\n\n"+
		"An MCP server scaffolded with [Dockyard](https://github.com/hurtener/dockyard).\n\n"+
		"## Layout\n\n"+
		"- `dockyard.app.yaml` — the manifest (server identity, tools, quality gates).\n"+
		"- `main.go` — the entrypoint: constructs the server, serves stdio.\n"+
		"- `greet.go` — the example `greet` tool and its handler.\n"+
		"- `greet_test.go` — a contract test for the example tool.\n"+
		"- `internal/contracts/` — the typed Go contract structs (the source of\n"+
		"  truth, P1) plus their **generated** JSON Schema and TypeScript. Never\n"+
		"  hand-edit a generated file; change the Go struct and regenerate.\n\n"+
		"## Run\n\n"+
		"```sh\n"+
		"go run .          # serve over stdio\n"+
		"go test ./...     # run the contract tests\n"+
		"```\n\n"+
		"## Next steps\n\n"+
		"- Add a tool: write a handler and a `tool.New(...)` call in `greet.go`.\n"+
		"- Edit a contract: change the struct in `internal/contracts`, then\n"+
		"  regenerate the schema with `dockyard generate`.\n"+
		"- Validate the project with `dockyard validate`.\n",
		titleCase(o.Name))
}

// gitignoreContent is the scaffolded project's .gitignore. Generated contract
// artifacts are intentionally NOT ignored — they are checked in so a clone
// builds without a generate step, and 'dockyard validate' diffs them.
const gitignoreContent = `# Build output
/bin/
/dist/

# Go test artifacts
*.test
coverage.out
`
