// Package generate is the engine behind `dockyard generate` — the contract-first
// code generation verb (RFC §6, §9.1).
//
// It drives the Design A pipeline (RFC §6.2) over a Dockyard project: a tool's
// typed Go input and output structs are the single source of truth (P1), and
// generate produces the downstream artifacts — the per-contract JSON Schema
// files and the TypeScript contract types — never the other way round.
//
// # The two halves
//
// TypeScript is generated in-process: internal/codegen.TypeScriptForDir reads
// the project's internal/contracts/*.go source and emits contracts.ts. It needs
// only the Go source text, so the `dockyard` binary runs it directly.
//
// JSON Schema is generated by an ephemeral generator (D-081). The schema engine
// — github.com/google/jsonschema-go — works from a reflect.Type, and the
// `dockyard` binary cannot reflect on a separate project's compiled contract
// types; internal/codegen is also not importable from a scaffolded project's
// module. So generate templates a tiny Go program into a temp directory inside
// the project, one that imports the project's own contracts package and the
// public runtime/tool API, and `go run`s it. That program reflects on the real
// contract types and writes each schema file with runtime/tool.MarshalSchema —
// the same deterministic marshaller the rest of the pipeline uses.
//
// # Idempotency
//
// Both generators are deterministic: identical contract source yields
// byte-identical output. Run is therefore idempotent — a second run with no
// source change rewrites the same bytes and Result.Changed is empty. This is a
// binding Phase 18 acceptance criterion and the property `dockyard validate`'s
// stale-codegen check relies on.
package generate
