package generate

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hurtener/dockyard/internal/codegen"
	"github.com/hurtener/dockyard/internal/manifest"
)

// ErrGenerate is the sentinel wrapping every generate failure. Callers branch
// with errors.Is(err, ErrGenerate).
var ErrGenerate = errors.New("dockyard/internal/generate: code generation failed")

// ContractsDir is the project-relative directory holding the Go contract source
// and its generated artifacts. It is the directory `dockyard new` scaffolds and
// the one the codegen pipeline reads and writes (RFC §6.2).
const ContractsDir = "internal/contracts"

// contractsTSFile is the generated TypeScript file name within ContractsDir.
const contractsTSFile = "contracts.ts"

// Options configures one generate run.
type Options struct {
	// ProjectDir is the root of the Dockyard project — the directory holding
	// dockyard.app.yaml. Required.
	ProjectDir string
	// Manifest is the loaded, validated manifest. Required: generate reads the
	// tools list to know which contract types to produce schemas for.
	Manifest *manifest.Manifest
}

// Result reports what a generate run produced.
type Result struct {
	// Written is every generated file, project-relative, sorted.
	Written []string
	// Changed is the subset of Written whose bytes differed from what was
	// already on disk. An empty Changed on a rerun is the idempotency
	// guarantee made observable (RFC §6.2): no source change ⇒ no diff.
	Changed []string
}

// TSFileName is the project-relative path of the generated TypeScript contract
// file. It is exported so `dockyard validate`'s stale-codegen check locates the
// same file generate writes.
func TSFileName() string {
	return filepath.ToSlash(filepath.Join(ContractsDir, contractsTSFile))
}

// Plan runs the Design A codegen pipeline (RFC §6.2) for the project and
// returns the would-be generated files keyed by project-relative path —
// without writing anything. It is the dry-run core of Run: `dockyard generate`
// calls Run (Plan + write); `dockyard validate`'s stale-codegen check calls
// Plan and diffs the result against what is on disk.
//
// TypeScript is generated in-process from the contracts/*.go source. JSON
// Schema is generated by an ephemeral generator `go run` inside the project
// (D-081), because the schema engine reflects on real Go types the `dockyard`
// binary cannot see. The ephemeral generator writes its schema files into a
// temp directory, so Plan still touches the filesystem there, but never mutates
// the project's committed contract artifacts.
//
// Plan is deterministic: identical contract source yields byte-identical
// output. It builds fresh state per call and holds no shared mutable state.
func Plan(opts Options) (map[string][]byte, error) {
	if opts.ProjectDir == "" {
		return nil, fmt.Errorf("%w: ProjectDir is required", ErrGenerate)
	}
	if opts.Manifest == nil {
		return nil, fmt.Errorf("%w: Manifest is required", ErrGenerate)
	}
	contractsDir := filepath.Join(opts.ProjectDir, filepath.FromSlash(ContractsDir))
	if info, err := os.Stat(contractsDir); err != nil || !info.IsDir() {
		return nil, fmt.Errorf("%w: contracts directory %s not found — is this a Dockyard project?",
			ErrGenerate, ContractsDir)
	}

	planned := map[string][]byte{}

	// --- TypeScript half — pure source, generated in-process. ---------------
	ts, err := codegen.TypeScriptForDir(contractsDir)
	if err != nil {
		return nil, fmt.Errorf("%w: typescript: %w", ErrGenerate, err)
	}
	planned[TSFileName()] = ts

	// --- JSON Schema half — ephemeral in-project generator (D-081). ---------
	schemas, err := runSchemaGenerator(opts.ProjectDir, opts.Manifest)
	if err != nil {
		return nil, err
	}
	for rel, content := range schemas {
		planned[rel] = content
	}
	return planned, nil
}

// Run executes the Design A codegen pipeline (RFC §6.2) for the project: it
// regenerates the TypeScript contract types and the per-contract JSON Schema
// files from the Go contract structs, writing the result into the project.
//
// Run is idempotent: a second invocation with no contract-source change writes
// byte-identical files and returns an empty Result.Changed. Run builds fresh
// state per call and holds no shared mutable state.
func Run(opts Options) (Result, error) {
	planned, err := Plan(opts)
	if err != nil {
		return Result{}, err
	}

	res := Result{}
	rels := make([]string, 0, len(planned))
	for rel := range planned {
		rels = append(rels, rel)
	}
	sort.Strings(rels)
	for _, rel := range rels {
		full := filepath.Join(opts.ProjectDir, filepath.FromSlash(rel))
		changed, err := writeIfChanged(full, planned[rel])
		if err != nil {
			return Result{}, fmt.Errorf("%w: write %s: %w", ErrGenerate, rel, err)
		}
		res.Written = append(res.Written, rel)
		if changed {
			res.Changed = append(res.Changed, rel)
		}
	}
	return res, nil
}

// writeIfChanged writes content to path only when it differs from the file
// already there, and reports whether a write happened. Skipping an identical
// write keeps generate's mtime footprint minimal — a `dockyard dev` watcher
// (Phase 19) would otherwise see a spurious change event on every rerun.
func writeIfChanged(path string, content []byte) (bool, error) {
	existing, err := os.ReadFile(path) //nolint:gosec // path is composed from a caller-supplied project dir
	if err == nil && bytes.Equal(existing, content) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil { //nolint:gosec // a project directory is browsable, not a secret
		return false, err
	}
	if err := os.WriteFile(path, content, 0o644); err != nil { //nolint:gosec // generated source, not a secret
		return false, err
	}
	return true, nil
}

// SchemaFileName returns the project-relative path of a tool contract's
// generated JSON Schema file. side is "input" or "output". The convention
// matches `dockyard new`'s scaffold output: <ContractsDir>/<tool>_<side>.schema.json.
//
// It is exported so `dockyard validate`'s stale-codegen check locates the same
// files generate writes.
func SchemaFileName(toolName, side string) string {
	return filepath.ToSlash(filepath.Join(ContractsDir, toolName+"_"+side+".schema.json"))
}

// runSchemaGenerator templates the ephemeral schema generator into a temp
// directory inside the project, `go run`s it, and returns the generated schema
// files keyed by project-relative path. See D-081 for why generation cannot
// happen in the `dockyard` binary directly.
func runSchemaGenerator(projectDir string, m *manifest.Manifest) (map[string][]byte, error) {
	modulePath, err := readModulePath(projectDir)
	if err != nil {
		return nil, err
	}
	contractTypes, err := resolveContractImports(m, modulePath)
	if err != nil {
		return nil, err
	}

	// The generator program lives in a temp dir inside the project module so it
	// can import the project's own contract packages. It writes its schema
	// files into outDir — a separate temp dir, never the project's committed
	// internal/contracts tree — so Plan stays a true dry run.
	genDir, err := os.MkdirTemp(projectDir, ".dockyard-gen-*")
	if err != nil {
		return nil, fmt.Errorf("%w: create generator temp dir: %w", ErrGenerate, err)
	}
	defer func() { _ = os.RemoveAll(genDir) }()
	outDir, err := os.MkdirTemp("", "dockyard-schemas-*")
	if err != nil {
		return nil, fmt.Errorf("%w: create schema output temp dir: %w", ErrGenerate, err)
	}
	defer func() { _ = os.RemoveAll(outDir) }()

	src, err := renderGeneratorProgram(m, contractTypes)
	if err != nil {
		return nil, err
	}
	mainGo := filepath.Join(genDir, "main.go")
	if err := os.WriteFile(mainGo, []byte(src), 0o644); err != nil { //nolint:gosec // generated source, not a secret
		return nil, fmt.Errorf("%w: write generator program: %w", ErrGenerate, err)
	}

	// Run the generator as a package directory ("./.dockyard-gen-XXX"), not a
	// bare file: `go run <file>` compiles the file as the pseudo-package
	// command-line-arguments, which is not rooted in the module and so cannot
	// import the project's internal/contracts package. Running the directory
	// makes it a real package inside the project module — and the directory is
	// a child of the project root, the parent of internal/, so the internal-
	// package import rule is satisfied.
	genPkg := "./" + filepath.Base(genDir)
	cmd := exec.Command("go", "run", genPkg, outDir) //nolint:gosec // genPkg is a Dockyard-created temp dir; outDir is a temp dir
	cmd.Dir = projectDir
	cmd.Env = append(os.Environ(), "CGO_ENABLED=0")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("%w: schema generator failed: %w\n%s",
			ErrGenerate, err, strings.TrimSpace(stderr.String()))
	}

	out := map[string][]byte{}
	for _, t := range m.Tools {
		for _, side := range []string{"input", "output"} {
			flat := t.Name + "_" + side + ".schema.json"
			content, err := os.ReadFile(filepath.Join(outDir, flat)) //nolint:gosec // outDir is a Dockyard-created temp dir
			if err != nil {
				return nil, fmt.Errorf("%w: schema generator did not produce %s: %w",
					ErrGenerate, SchemaFileName(t.Name, side), err)
			}
			out[SchemaFileName(t.Name, side)] = content
		}
	}
	return out, nil
}

// contractImport is one contracts package referenced by the manifest, with the
// import alias the generator program uses for it.
type contractImport struct {
	alias string
	path  string // import path, e.g. "<module>/internal/contracts"
}

// resolveContractImports collects the distinct contract package import paths the
// manifest references, keyed by the manifest-relative package and assigning each
// a stable alias. A tool's input/output ref is "<package path>.<TypeName>"; the
// package path is project-module-relative, so the generator program imports it
// as "<module>/<package path>".
func resolveContractImports(m *manifest.Manifest, modulePath string) (map[string]contractImport, error) {
	byPath := map[string]contractImport{}
	for _, t := range m.Tools {
		for _, ref := range []string{t.Input, t.Output} {
			parsed, err := manifest.ParseContractReference(ref)
			if err != nil {
				return nil, fmt.Errorf("%w: tool %q: %w", ErrGenerate, t.Name, err)
			}
			if _, ok := byPath[parsed.Package]; ok {
				continue
			}
			byPath[parsed.Package] = contractImport{
				alias: fmt.Sprintf("c%d", len(byPath)),
				path:  modulePath + "/" + parsed.Package,
			}
		}
	}
	return byPath, nil
}
