package generate

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hurtener/dockyard/internal/manifest"
)

// renderGeneratorProgram templates the ephemeral schema generator (D-081): a
// self-contained Go main that imports the project's own contract packages and
// the public runtime/tool API, reflects on each tool's real contract types, and
// writes each <tool>_<side>.schema.json file with the deterministic
// runtime/tool.MarshalSchema marshaller.
//
// The program is generated, not hand-written by the developer; it lives only
// for the duration of one `go run` and is deleted afterwards. It depends solely
// on public packages, so it compiles inside the project's own module — the
// project cannot import Dockyard's internal/ packages.
func renderGeneratorProgram(m *manifest.Manifest, imports map[string]contractImport, enums map[string][]any) (string, error) {
	if len(m.Tools) == 0 {
		return "", fmt.Errorf("%w: manifest declares no tools", ErrGenerate)
	}

	var b strings.Builder
	b.WriteString("// Code generated by dockyard generate; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Ephemeral schema generator — see Dockyard D-081. Templated into the\n")
	b.WriteString("// project, `go run` with an output directory as os.Args[1], then deleted.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"path/filepath\"\n\n")
	b.WriteString("\t\"github.com/google/jsonschema-go/jsonschema\"\n")
	b.WriteString("\t\"github.com/hurtener/dockyard/runtime/tool\"\n")

	aliases := make([]contractImport, 0, len(imports))
	for _, ci := range imports {
		aliases = append(aliases, ci)
	}
	sort.Slice(aliases, func(i, j int) bool { return aliases[i].alias < aliases[j].alias })
	for _, ci := range aliases {
		fmt.Fprintf(&b, "\t%s %q\n", ci.alias, ci.path)
	}
	b.WriteString(")\n\n")

	b.WriteString("func main() {\n")
	b.WriteString("\tif len(os.Args) < 2 {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, \"usage: generator <output-dir>\")\n")
	b.WriteString("\t\tos.Exit(2)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := run(os.Args[1]); err != nil {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("func run(outDir string) error {\n")
	b.WriteString("\topts := []tool.SchemaOption{\n")
	names := make([]string, 0, len(enums))
	for name := range enums {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "\t\ttool.WithEnum(%q", name)
		for _, value := range enums[name] {
			literal, err := json.Marshal(value)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&b, ", %s", literal)
		}
		b.WriteString("),\n")
	}
	b.WriteString("\t}\n")
	for _, t := range m.Tools {
		in, err := manifest.ParseContractReference(t.Input)
		if err != nil {
			return "", fmt.Errorf("%w: tool %q input: %w", ErrGenerate, t.Name, err)
		}
		out, err := manifest.ParseContractReference(t.Output)
		if err != nil {
			return "", fmt.Errorf("%w: tool %q output: %w", ErrGenerate, t.Name, err)
		}
		inType := imports[in.Package].alias + "." + in.TypeName
		outType := imports[out.Package].alias + "." + out.TypeName
		fmt.Fprintf(&b, "\t{\n")
		fmt.Fprintf(&b, "\t\tin, err := tool.InputSchemaFor[%s](opts...)\n", inType)
		fmt.Fprintf(&b, "\t\tif err != nil {\n")
		fmt.Fprintf(&b, "\t\t\treturn fmt.Errorf(\"tool %s: %%w\", err)\n", t.Name)
		fmt.Fprintf(&b, "\t\t}\n")
		fmt.Fprintf(&b, "\t\tout, err := tool.OutputSchemaFor[%s](opts...)\n", outType)
		fmt.Fprintf(&b, "\t\tif err != nil { return fmt.Errorf(\"tool %s: %%w\", err) }\n", t.Name)
		fmt.Fprintf(&b, "\t\tif err := writeSchema(outDir, %q, in); err != nil {\n",
			t.Name+"_input.schema.json")
		fmt.Fprintf(&b, "\t\t\treturn err\n")
		fmt.Fprintf(&b, "\t\t}\n")
		fmt.Fprintf(&b, "\t\tif err := writeSchema(outDir, %q, out); err != nil {\n",
			t.Name+"_output.schema.json")
		fmt.Fprintf(&b, "\t\t\treturn err\n")
		fmt.Fprintf(&b, "\t\t}\n")
		fmt.Fprintf(&b, "\t}\n")
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")

	b.WriteString("func writeSchema(outDir, name string, s *jsonschema.Schema) error {\n")
	b.WriteString("\tdata, err := tool.MarshalSchema(s)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"marshal %s: %w\", name, err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := os.WriteFile(filepath.Join(outDir, name), data, 0o644); err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"write %s: %w\", name, err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
	return b.String(), nil
}

// readModulePath returns the Go module path declared in the project's go.mod.
// It is exported helper-grade: callers building an import path for a project
// package need the module prefix.
func readModulePath(projectDir string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(projectDir, "go.mod")) //nolint:gosec // composed from a caller-supplied project dir
	if err != nil {
		return "", fmt.Errorf("%w: read go.mod: %w", ErrGenerate, err)
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if rest, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(rest), nil
		}
	}
	return "", fmt.Errorf("%w: go.mod declares no module path", ErrGenerate)
}
